function LEGAL_KB() {
    return [
        ['PRCA','Advance cap — residential','PRCA 1991 §10: a residential landlord may not demand more than 1 month\'s rent as advance without the Rent Controller\'s consent. KRTaker flags any residential lease exceeding the cap before revenue can move.','residential advance cap prca 10 one month'],
        ['PRCA','Advance cap — commercial','PRCA 1991 §23: commercial premises advances are capped at 3 months\' rent. Any excess must be returned or adjusted at the tenant\'s demand.','commercial advance cap prca 23 three months'],
        ['PRCA','Rent hike limit','PRCA 1991: for residential premises the monthly rent may not be increased by more than 5% every 3 years without rent-controller approval. Notices must be in writing.','rent hike increase 5 percent three years prca'],
        ['PRCA','Signed receipts','PRCA 1991 §13: the landlord must issue a signed, dated receipt for every rent payment — even partial payments. KRTaker issues a cryptographically signed receipt (PRCA §13) for every payment automatically.','receipt signed prca 13 payment proof'],
        ['PRCA','Eviction protection','PRCA 1991 §18: a tenant may only be evicted on statutory grounds (e.g. 3+ months rent unpaid, owner\'s genuine need, breach of terms) through the Rent Controller. No digital lockouts, utility cuts or self-help evictions are permitted.','eviction protection prca 18 lockout unpaid grounds'],
        ['TPA','Lease registration gate','TPA 1882 §107 & Registration Act 1908 §17(1)(d): any lease for more than 12 months must be registered at the Sub-Registry. Unregistered long leases cannot activate ledgers — KRTaker holds them as Pending Registration.','tpa 107 registration lease 12 months deed sub-registry'],
        ['TPA','Deed checklist','For Sub-Registry registration you need: rent deed (2 copies), tenant NID copy, landlord CS/SA/RS/BS khatian or e-porcha, holding tax paid copies, valuation, stamp duty. KRTaker prepares the checklist automatically.','deed checklist registration documents khatian stamp duty'],
        ['TAX','TDS on rent','Income Tax Act 2023 §109: rent payments attract TDS — 10% on commercial rents and 2% on residential rents paid to individual landlords (verify your exact rate with the current SRO). Withholding is split and tracked per invoice.','tds withholding rent tax 109 commercial 10 residential 2'],
        ['TAX','Capital gains on property','Income Tax Act 2023 §128: gains on transfer of property are taxed at 15%. Wealth surcharge brackets apply above ৳10Cr/৳20Cr slabs. KRTaker\'s estimator computes gain, tax and net proceeds.','capital gain property transfer 128 15 percent surcharge wealth'],
        ['TAX','Minimum tax & surcharge','IT Act 2023 minimum tax applies regardless of losses; wealth surcharge kicks in on taxable income above ৳4Cr (higher slabs at ৳20Cr/৳50Cr+). KRTaker flags minimum-tax cases automatically.','minimum tax wealth surcharge brackets 4cr 20cr 50cr'],
        ['HOLDING','Holding tax formula','Holding tax = NAV × city corporation rate. NAV (Net Annual Value) = Gross Annual Rent × 75% (25% statutory deduction for repairs/collection). GAR → NAV → rate, exactly as KRTaker computes it.','holding tax gar nav annual value rate formula city corporation'],
        ['HOLDING','Dhaka North / South rates','Dhaka North & South city corporations apply their own annual rate on NAV (roughly 5–7%, revised periodically). Holding tax paid copies are required for lease registration and NID address change.','dhaka north south rate holding tax percent'],
        ['KHIATAN','Khatian verification','Land title is verified against CS/SA/RS/BS khatian records and the e-porcha from land.gov.bd. KRTaker cross-references the khatian before onboarding any asset.','khatian cs sa rs bs e-porcha land.gov.bd title verification'],
        ['NRB','Remittance repatriation','NRB landlords repatriate rental income under NRTA/NITA with forms IT10B, Form TM and QA-22. Rental income is taxable in Bangladesh; final-tax treatment depends on your TIN status.','nrb remittance repatriation nrta nita it10b tm qa-22'],
        ['MAINT','Maintenance liability — structural','Structural repairs (roof, external walls, main structure, plumbing mains) are the landlord\'s responsibility under TPA 1882 §108 and standard practice. KRTaker assigns liability Landlord.','maintenance liability structural roof wall landlord tpa 108'],
        ['MAINT','Maintenance liability — tenant','Repairs caused by the tenant\'s use (broken fittings, cosmetic damage, appliance misuse) are the tenant\'s responsibility. KRTaker assigns liability Tenant and can draft the deduction letter.','maintenance liability tenant cosmetic damage fitting'],
        ['MAINT','Common areas & shared systems','Lifts, generators, water pumps, common-area lighting and security are shared liabilities — apportioned across units per lease. KRTaker flags shared liability on tickets.','maintenance liability shared common area lift generator pump'],
        ['PRCA','Rent due & default interest','Rent falls due per the lease (usually the 1st). PRCA does not allow arbitrary late fees; any default interest must be in the written lease. KRTaker tracks due dates and issues compliant reminders.','rent due default late fee reminder prca'],
    ];
}
