function seed_email_tpl($id) {
    $tpls = [
'otp' => [
'Your KRTaker verification code: {{code}}',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">KRTaker<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <h1 style="margin:0 0 8px;font-size:20px;color:#101828">Verify your email</h1>
    <p style="margin:0 0 22px;color:#475467;font-size:14px;line-height:1.6">Hi {{name}}, use the one-time code below to activate your KRTaker workspace.</p>
    <div style="border:2px dashed #2F80ED;background:#F6F9FE;border-radius:14px;padding:20px 14px;text-align:center;font-size:34px;font-weight:800;color:#2F80ED;letter-spacing:10px;padding-left:24px">{{code}}</div>
    <p style="margin:20px 0 0;color:#667085;font-size:12.5px;line-height:1.8">⏱ The code expires in {{expiry}}.<br>🔒 Never share this code. KRTaker will never ask for your password or OTP over the phone.</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">
    KRTaker · Dhaka, Bangladesh<br>support@krtaker.com · +880 1722-759646<br>If you did not request this code, ignore this email — your account is safe.
  </div>
</div>
HTML,
],
'welcome' => [
'Welcome to KRTaker 🎉 — your trial is live',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">KRTaker<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <h1 style="margin:0 0 8px;font-size:20px;color:#101828">Welcome aboard, {{name}} 🎉</h1>
    <p style="margin:0 0 8px;color:#475467;font-size:14px;line-height:1.7">Your KRTaker workspace is active on a <b>14-day free trial</b> until <b>{{trial_end}}</b> — no card required.</p>
    <p style="margin:0 0 22px;color:#475467;font-size:14px;line-height:1.7">Add your first property, invite your team, and let KR — your AI caretaker — handle rent, receipts, TDS and compliance.</p>
    <a href="{{workspace_url}}" style="display:inline-block;background:#2F80ED;color:#fff;padding:13px 28px;border-radius:12px;text-decoration:none;font-weight:700;font-size:14px">Open your workspace →</a>
    <p style="margin:22px 0 0;color:#8A94A6;font-size:12.5px;line-height:1.7">Questions? Reply to this email — we reply within 24 hours. 🇧🇩 Built for Bangladeshi property owners.</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh<br>support@krtaker.com · +880 1722-759646</div>
</div>
HTML,
],
'collections' => [
'KRTaker — {{unpaid}} unpaid rent invoice(s)',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#E67E22,#D35400);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">Overdue collections<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <p style="margin:0 0 6px;color:#475467;font-size:14px"><b>{{unpaid}}</b> unpaid invoice(s) · <b>৳{{total}}</b> outstanding</p>
    <table style="width:100%;border-collapse:collapse;margin-top:14px">{{items}}</table>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com<br>This digest is generated by KR, your AI caretaker.</div>
</div>
HTML,
],
'rent_reminder' => [
'Rent reminder — {{invoice_id}} ({{month}})',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">Rent reminder<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <p style="margin:0 0 14px;color:#475467;font-size:14px">Dear {{tenant_name}},</p>
    <p style="margin:0 0 14px;color:#475467;font-size:14px;line-height:1.7">Invoice <b>{{invoice_id}}</b> for <b>{{month}}</b> — <b>৳{{amount}}</b> — is due for <b>{{property}}</b> ({{unit}}).</p>
    <div style="background:#FFF4E5;border:1px solid #FFD9A0;border-radius:12px;padding:14px 18px;font-size:13px;color:#7A4A00;margin-bottom:16px">⚠️ <b>Tier {{tier}} reminder</b> · {{days_overdue}} day(s) past due — {{tier_note}}</div>
    <div style="margin:0 0 16px"><a href="{{pay_url}}" style="display:inline-block;background:#2F80ED;color:#ffffff;padding:13px 26px;border-radius:10px;font-size:14px;font-weight:700;text-decoration:none">💳 Pay now — ৳{{amount}}</a></div>
    <div style="background:#F6F9FE;border:1px solid #E4EAF3;border-radius:12px;padding:14px 18px;font-size:13px;color:#1A2433;margin-bottom:18px">Prefer bKash, Nagad or your KRTaker tenant portal? The button takes you straight to the secure checkout for invoice <b>{{invoice_id}}</b>. {{late_fee}}</div>
    <p style="margin:0;color:#8A94A6;font-size:12.5px">— KRTaker, your AI caretaker 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'invoice' => [
'Your rent invoice {{invoice_id}} ({{month}}) — KRTaker',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">Rent invoice<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <p style="margin:0 0 16px;color:#475467;font-size:14px">Dear {{tenant_name}},</p>
    <div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Invoice</span><b>{{invoice_id}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Month</span><b>{{month}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Property</span><b>{{property}} ({{unit}})</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Amount</span><b>৳{{amount}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:14px 18px;background:#F6F9FE;font-size:14px"><span style="color:#8A94A6;font-weight:600">Balance due</span><b style="color:{{due_color}};font-size:16px">৳{{due}}</b></div>
    </div>
    <p style="margin:0 0 16px;color:#475467;font-size:13.5px;line-height:1.7">Pay via bKash, Nagad or SSLCommerz — the button takes you straight to the secure checkout for invoice <b>{{invoice_id}}</b>. A printable copy is available inside your KRTaker dashboard.</p>
    <div style="margin:0 0 16px"><a href="{{pay_url}}" style="display:inline-block;background:#2F80ED;color:#ffffff;padding:13px 26px;border-radius:10px;font-size:14px;font-weight:700;text-decoration:none">💳 Pay now — ৳{{due}}</a></div>
    <p style="margin:0;color:#8A94A6;font-size:12.5px">— KRTaker, your AI caretaker 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'receipt' => [
'Payment receipt {{receipt_id}} — KRTaker',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#27AE60,#1E8449);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">Payment received ✓<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <p style="margin:0 0 16px;color:#475467;font-size:14px">Dear {{tenant_name}}, thank you for your payment.</p>
    <div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Receipt</span><b>{{receipt_id}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Date</span><b>{{date}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Amount</span><b style="font-size:16px">৳{{amount}}</b></div>
      <div style="padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:12.5px;color:#475467;line-height:1.7"><span style="color:#8A94A6">In words:</span><br>{{amount_words_en}}<br>{{amount_words_bn}}</div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Method</span><b>{{method}} {{ref}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;font-size:13px"><span style="color:#8A94A6">For</span><b>{{property}} ({{unit}}) · {{month}}</b></div>
    </div>
    <p style="margin:0;color:#8A94A6;font-size:12.5px;line-height:1.7">Keep this email for your records — it is your official money receipt. — KRTaker, your AI caretaker 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'renewal_status' => [
'Your lease renewal {{status}} — {{property}} ({{lease}})',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">Lease renewal {{status}}<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <p style="margin:0 0 16px;color:#475467;font-size:14px">Dear {{tenant_name}},</p>
    <div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Property</span><b>{{property}} ({{unit}})</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Lease</span><b>{{lease}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Status</span><b style="color:{{status_color}}">{{status}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">New end date</span><b>{{new_end}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:14px 18px;background:#F6F9FE;font-size:14px"><span style="color:#8A94A6;font-weight:600">Monthly rent</span><b>৳{{new_rent}}</b></div>
    </div>
    <p style="margin:0 0 18px;color:#475467;font-size:13.5px;line-height:1.7">{{note}}</p>
    <p style="margin:0;color:#8A94A6;font-size:12.5px">Any questions? Reply to this email — we reply within 24 hours. — KRTaker, your AI caretaker 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'premium_welcome' => [
'👑 Your {{tier_label}} is active — your AI caretaker is on duty',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#8E2DE2,#4A00E0);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">👑 {{tier_label}}<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · REMOTE CARETAKER</span></div>
  </div>
  <div style="padding:32px">
    <h1 style="margin:0 0 8px;font-size:20px;color:#101828">Your caretaker is on duty, {{name}}</h1>
    <p style="margin:0 0 18px;color:#475467;font-size:14px;line-height:1.7">Your <b>{{tier_label}}</b> subscription for <b>{{property}}</b> is live. KR will now chase rent, settle utility bills, coordinate repairs and keep you posted.</p>
    <div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Plan</span><b>{{tier_label}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Property under care</span><b>{{property}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Billing</span><b>{{cycle}} · {{price}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:14px 18px;background:#F6F9FE;font-size:14px"><span style="color:#8A94A6;font-weight:600">Next invoice</span><b>{{next_invoice}}</b></div>
    </div>
    <a href="{{workspace_url}}" style="display:inline-block;background:#2F80ED;color:#fff;padding:13px 28px;border-radius:12px;text-decoration:none;font-weight:700;font-size:14px">Open caretaker dashboard →</a>
    <p style="margin:22px 0 0;color:#8A94A6;font-size:12.5px;line-height:1.7">Questions? Reply to this email — your concierge line replies within 24 hours. 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'move_out' => [
'Move-out completed — {{property}} · {{unit_name}} · {{status}}',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#101828,#344054);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">🚪 Move-out completed<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <h1 style="margin:0 0 8px;font-size:20px;color:#101828">Settlement statement, {{name}}</h1>
    <p style="margin:0 0 18px;color:#475467;font-size:14px;line-height:1.7">Your tenancy at <b>{{property}}</b> — <b>{{unit_name}}</b> was formally closed on <b>{{move_out_date}}</b>. The final settlement is attached below.</p>
    <div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Lease</span><b>{{lease}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Rent arrears</span><b>৳{{rent_due}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Utility dues</span><b>৳{{util_due}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Damage deductions</span><b>৳{{dmg_due}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Advance deposit</span><b>৳{{deposit}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:14px 18px;background:#F6F9FE;font-size:14px"><span style="color:#8A94A6;font-weight:600">Final balance</span><b style="color:{{status_color}}">৳{{balance}} · {{status}}</b></div>
    </div>
    <a href="{{workspace_url}}" style="display:inline-block;background:#2F80ED;color:#fff;padding:13px 28px;border-radius:12px;text-decoration:none;font-weight:700;font-size:14px">View settlement certificate →</a>
    <p style="margin:22px 0 0;color:#8A94A6;font-size:12.5px;line-height:1.7">The deposit refund (if any) is processed within 5 working days. Thank you for renting with KRTaker. 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
    ];
    return $tpls[$id] ?? ['', ''];
}
function seed_templates($pdo) {
    $names = [
        'LSE-STD' => ['lease', 'Standard Tenancy Agreement', 'Tenancy Agreement'],
        'SRV-STD' => ['service', 'Standard Service Contract', 'Service Contract'],
        'RCP-RENT' => ['receipt', 'Rent Receipt', 'Money Receipt — Rent'],
        'RCP-ADV' => ['receipt', 'Advance / Security Deposit Receipt', 'Money Receipt — Advance'],
        'RCP-SVC' => ['receipt', 'Service Charge Receipt', 'Money Receipt — Service Charges'],
        'RCP-GEN' => ['receipt', 'General Payment Receipt', 'Money Receipt — Payment Received'],
    ];
    foreach ($names as $id => $n) {
        $body = seed_tpl_body($id);
        $st = $pdo->prepare('SELECT COUNT(*) FROM doc_templates WHERE id=?'); $st->execute([$id]);
        if (!(int)$st->fetchColumn()) {
            $pdo->prepare('INSERT INTO doc_templates (id,kind,name,title,body,is_default,updated_by) VALUES (?,?,?,?,?,1,?)')
                ->execute([$id, $n[0], $n[1], $n[2], $body, 'system']);
        }
    }
    $emails = ['otp' => 'Verification (OTP) Email', 'welcome' => 'Welcome Email', 'collections' => 'Collections Digest', 'rent_reminder' => 'Rent Reminder', 'invoice' => 'Invoice Email', 'receipt' => 'Receipt Email', 'renewal_status' => 'Lease Renewal Status', 'premium_welcome' => 'Caretaker Subscription Confirmation', 'move_out' => 'Move-out / Settlement Notice'];
    foreach ($emails as $id => $nm) {
        list($subj, $body) = seed_email_tpl($id);
        $st = $pdo->prepare('SELECT COUNT(*) FROM email_templates WHERE id=?'); $st->execute([$id]);
        if (!(int)$st->fetchColumn()) {
            $pdo->prepare('INSERT INTO email_templates (id,name,subject,body,updated_by) VALUES (?,?,?,?,?)')
                ->execute([$id, $nm, $subj, $body, 'system']);
        }
    }
    /* Phase 15: refresh stock rent_reminder template with tier placeholders (only when not customized) */
    $st = $pdo->prepare("SELECT body FROM email_templates WHERE id='rent_reminder'"); $st->execute();
    $rr = $st->fetchColumn();
    if ($rr !== false && strpos($rr, '{{tier_note}}') === false) {
        list($s2, $b2) = seed_email_tpl('rent_reminder');
        $pdo->prepare("UPDATE email_templates SET subject=?, body=?, updated_by='system' WHERE id='rent_reminder'")->execute([$s2, $b2]);
    }
}
function email_render($id, $vars) {
    $pdo = db();
    $st = $pdo->prepare('SELECT * FROM email_templates WHERE id=?'); $st->execute([$id]);
    $t = $st->fetch(PDO::FETCH_ASSOC);
    if ($t) { $subj = $t['subject']; $body = $t['body']; }
    else { list($subj, $body) = seed_email_tpl($id); }
    return [render_merge($subj, $vars), render_merge($body, $vars)];
}
function org_vars($u) {
    $pdo = db();
    $m = [];
    foreach ($pdo->query("SELECT k,v FROM platform_meta WHERE k LIKE 'org\\_%' ESCAPE '\\'") as $r) $m[$r['k']] = $r['v'];
    return [
        'org_name'    => esc($m['org_name'] ?? (($u['org'] ?? '') ?: ($u['name'] ?? 'KRTaker'))),
        'org_phone'   => esc($m['org_phone'] ?? ($u['phone'] ?? '')),
        'org_email'   => esc($m['org_email'] ?? ($u['email'] ?? 'support@krtaker.com')),
        'org_address' => esc($m['org_address'] ?? 'Dhaka, Bangladesh'),
        'today'       => gmdate('d M Y'),
    ];
}
function tpl_vars_for($u, $kind, $ref) {
    $pdo = db();
    $vars = org_vars($u);
    $links = [];
    if ($kind === 'lease') {
        $st = $pdo->prepare('SELECT l.id AS lid, l.u AS uid, l.t AS tid, l.start, l.end, l.rent, l.adv, l.res, l.reg_office, l.reg_deed,
                             u.name AS uname, u.floor, u.p AS pid, p.name AS pname, p.jur, p.holding,
                             t.name AS tname, t.phone AS tphone, t.email AS temail, t.nid AS tnid
                             FROM leases l JOIN units u ON u.id=l.u JOIN properties p ON p.id=u.p JOIN tenants t ON t.id=l.t WHERE l.id=?');
        $st->execute([$ref]); $r = $st->fetch(PDO::FETCH_ASSOC);
        if (!$r) return null;
        $res = ((int)($r['res'] ?? 1)) === 1;
        $vars += [
            'lease_id' => esc($r['lid']), 'lease_start' => esc($r['start']), 'lease_end' => esc($r['end']),
            'rent' => money_bd((int)$r['rent']), 'rent_words' => num_to_words_en((int)$r['rent']),
            'advance' => money_bd((int)$r['adv']), 'advance_words' => num_to_words_en((int)$r['adv']),
            'reg_office' => esc($r['reg_office']), 'reg_deed' => esc($r['reg_deed']),
            'reg_note' => $res
                ? 'Rent is within the TPA 1882 §107 exemption — compulsory registration is not required, but registration is recommended for enforceability.'
                : 'This lease exceeds the TPA 1882 §107 exemption — it MUST be registered at the Sub-Registrar\'s office to be enforceable.',
            'tenant_name' => esc($r['tname']), 'tenant_phone' => esc($r['tphone']), 'tenant_nid' => esc($r['tnid']), 'tenant_email' => esc($r['temail']),
            'property_name' => esc($r['pname']), 'property_address' => esc(trim(trim($r['holding'] . ', ' . $r['jur']), ' ,')),
            'unit_name' => esc($r['uname']), 'unit_id' => esc($r['uid']), 'floor' => esc($r['floor']),
        ];
        $links = [
            'tenant_name' => ['tenants', $r['tid'], '👤'], 'tenant_phone' => ['tenants', $r['tid'], '👤'], 'tenant_nid' => ['tenants', $r['tid'], '👤'], 'tenant_email' => ['tenants', $r['tid'], '👤'],
            'property_name' => ['properties', $r['pid'], '🏢'], 'property_address' => ['properties', $r['pid'], '🏢'],
            'unit_name' => ['units', $r['uid'], '🚪'], 'unit_id' => ['units', $r['uid'], '🚪'], 'floor' => ['units', $r['uid'], '🚪'],
            'lease_id' => ['leases', $r['lid'], '📄'], 'lease_start' => ['leases', $r['lid'], '📄'], 'lease_end' => ['leases', $r['lid'], '📄'],
            'rent' => ['leases', $r['lid'], '📄'], 'rent_words' => ['leases', $r['lid'], '📄'], 'advance' => ['leases', $r['lid'], '📄'], 'advance_words' => ['leases', $r['lid'], '📄'],
        ];
    } elseif ($kind === 'service') {
        $st = $pdo->prepare('SELECT * FROM partners WHERE id=?'); $st->execute([$ref]);
        $r = $st->fetch(PDO::FETCH_ASSOC);
        if (!$r) return null;
        $vars += [
            'partner_name' => esc($r['name']), 'partner_trade' => esc($r['trade']),
            'partner_rating' => (string)(float)$r['rating'], 'partner_jobs' => (string)(int)$r['jobs'],
            'partner_status' => esc($r['status']), 'partner_email' => esc($r['sub_email'] ?? ''),
        ];
    } elseif ($kind === 'receipt') {
        $p = null; $inv = null;
        $st = $pdo->prepare('SELECT * FROM payments WHERE id=?'); $st->execute([$ref]); $p = $st->fetch(PDO::FETCH_ASSOC);
        if (!$p) { $st = $pdo->prepare('SELECT * FROM invoices WHERE id=?'); $st->execute([$ref]); $inv = $st->fetch(PDO::FETCH_ASSOC); }
        if (!$inv && !$p) {
            $st = $pdo->prepare('SELECT * FROM receipts WHERE id=?'); $st->execute([$ref]); $rec = $st->fetch(PDO::FETCH_ASSOC);
            if ($rec) { $st = $pdo->prepare('SELECT * FROM invoices WHERE id=?'); $st->execute([$rec['inv']]); $inv = $st->fetch(PDO::FETCH_ASSOC); }
        }
        if (!$inv && $p) { $st = $pdo->prepare('SELECT * FROM invoices WHERE id=?'); $st->execute([$p['inv']]); $inv = $st->fetch(PDO::FETCH_ASSOC); }
        if (!$p && $inv) { $st = $pdo->prepare("SELECT * FROM payments WHERE inv=? AND status='Success' ORDER BY date DESC, id DESC LIMIT 1"); $st->execute([$inv['id']]); $p = $st->fetch(PDO::FETCH_ASSOC); }
        if (!$inv) return null;
        $amt = $p ? (int)$p['amount'] : (int)$inv['net'];
        $st = $pdo->prepare('SELECT l.u AS uid, l.t AS tid FROM leases l WHERE l.id=?'); $st->execute([$inv['l']]);
        $l = $st->fetch(PDO::FETCH_ASSOC);
        $un = $pr = $te = null;
        if ($l) {
            $st = $pdo->prepare('SELECT name, floor, p FROM units WHERE id=?'); $st->execute([$l['uid']]); $un = $st->fetch(PDO::FETCH_ASSOC);
            $st = $pdo->prepare('SELECT name, jur, holding FROM properties WHERE id=?'); $st->execute([$un['p']]); $pr = $st->fetch(PDO::FETCH_ASSOC);
            $st = $pdo->prepare('SELECT name, phone FROM tenants WHERE id=?'); $st->execute([$l['tid']]); $te = $st->fetch(PDO::FETCH_ASSOC);
        }
        $vars += [
            'receipt_id' => esc($p ? $p['id'] : ('RCP-' . $inv['id'])),
            'date' => esc($p ? $p['date'] : gmdate('d M Y')),
            'invoice_id' => esc($inv['id']), 'month' => esc($inv['m']), 'lease_id' => esc($inv['l']),
            'amount' => money_bd($amt), 'amount_words_en' => num_to_words_en($amt), 'amount_words_bn' => num_to_words_bn($amt) . ' টাকা মাত্র',
            'method' => esc($p ? $p['method'] : '—'), 'ref' => esc($p ? $p['ref'] : '—'),
            'tenant_name' => esc($te['name'] ?? '—'), 'tenant_phone' => esc($te['phone'] ?? '—'),
            'property_name' => esc($pr['name'] ?? '—'), 'property_address' => esc($pr ? trim(trim($pr['holding'] . ', ' . $pr['jur']), ' ,') : '—'),
            'unit_name' => esc($un['name'] ?? '—'), 'unit_id' => esc($l['uid'] ?? '—'), 'floor' => esc($un['floor'] ?? '—'),
        ];
        $links = [
            'tenant_name' => ['tenants', $l['tid'] ?? '', '👤'], 'tenant_phone' => ['tenants', $l['tid'] ?? '', '👤'],
            'property_name' => ['properties', $un['p'] ?? '', '🏢'], 'property_address' => ['properties', $un['p'] ?? '', '🏢'],
            'unit_name' => ['units', $l['uid'] ?? '', '🚪'], 'unit_id' => ['units', $l['uid'] ?? '', '🚪'],
            'invoice_id' => ['invoices', $inv['id'], '🧾'], 'month' => ['invoices', $inv['id'], '🧾'],
            'lease_id' => ['leases', $inv['l'], '📄'],
            'receipt_id' => ['payments', $p['id'] ?? '', '💳'], 'amount' => ['payments', $p['id'] ?? '', '💳'], 'method' => ['payments', $p['id'] ?? '', '💳'], 'ref' => ['payments', $p['id'] ?? '', '💳'],
        ];
    } else {
        return null;
    }
    return ['vars' => $vars, 'links' => $links];
}
function tpl_print_page($tpl, $merged, $kind) {
    $sig = $kind === 'receipt'
        ? '<div class="sig"><div>Authorized signature</div></div>'
        : '<div class="sig"><div>Party 1 signature</div><div>Party 2 signature</div><div>Witness 1</div><div>Witness 2</div></div>';
    return '<!doctype html><html lang="en"><head><meta charset="utf-8"><title>' . esc($tpl['title']) . '</title><style>'
        . '*{box-sizing:border-box}body{font-family:Inter,"Hind Siliguri",Arial,sans-serif;color:#101828;margin:0;padding:32px;background:#F4F6FA}'
        . '.page{max-width:800px;margin:0 auto;background:#fff;border:1px solid #E4EAF3;border-radius:16px;padding:44px}'
        . '.brand{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #2F80ED;padding-bottom:14px;margin-bottom:18px}'
        . '.brand img{display:block;margin-bottom:3px}.brand b{font-size:19px;color:#2F80ED;letter-spacing:-.3px}.brand small{display:block;font-size:9.5px;letter-spacing:1.6px;color:#8A94A6;text-transform:uppercase}'
        . '.ttl{font-size:15px;font-weight:700;color:#1A2433}'
        . '.tpl-body{font-family:Inter,"Hind Siliguri",Arial,sans-serif;font-size:13.5px;line-height:1.9;color:#1A2433;white-space:pre-wrap}'
        . '.sig{margin-top:38px;display:grid;grid-template-columns:1fr 1fr;gap:26px}.sig div{border-top:1px dashed #98A2B3;padding-top:8px;font-size:12px;color:#475467}'
        . '.noprint{position:fixed;top:16px;right:16px}.btn{font:600 13px Inter;padding:9px 16px;border-radius:10px;border:1px solid #D0D5DD;background:#fff;cursor:pointer}.btn.p{background:#2F80ED;color:#fff;border-color:#2F80ED}'
        . '@media print{body{background:#fff;padding:0}.page{border:0;box-shadow:none}.noprint{display:none}}'
        . '</style></head><body><div class="noprint"><button class="btn" onclick="window.print()">🖨 Print / Save PDF</button></div><div class="page">'
        . '<div class="brand"><div>' . print_brand_img() . '<small>KEY RESPONSIBILITY TAKER</small></div><div class="ttl">' . esc($tpl['title']) . '</div></div>'
        . '<div class="tpl-body">' . $merged . '</div>'
        . $sig
        . '<div style="margin-top:26px;padding-top:12px;border-top:1px dashed #E4EAF3;font-size:11px;color:#8A94A6;text-align:center">System-generated by KRTaker — your AI caretaker · Verify at krtaker.com</div>'
        . '</div></body></html>';
}
function email_sample_vars($id) {
    switch ($id) {
        case 'otp': return ['code' => '483920', 'name' => 'Tahmina Akter', 'expiry' => '5 minutes'];
        case 'welcome': return ['name' => 'Tahmina Akter', 'trial_end' => '26 Jun 2026', 'workspace_url' => 'https://krtaker.com/dashboard-v2.html'];
        case 'collections': return ['unpaid' => '3', 'total' => '৳4,82,000', 'items' => '<tr><td style="padding:8px 10px;border-bottom:1px solid #E4EAF3;font-size:13px"><b>INV-2026-0011</b><br><span style="color:#8A94A6;font-size:11px">Sultana Rahman · Green View Residency</span></td><td style="padding:8px 10px;border-bottom:1px solid #E4EAF3;font-size:13px">2026-06</td><td style="padding:8px 10px;border-bottom:1px solid #E4EAF3;font-size:13px;text-align:right">৳32,000</td></tr><tr><td style="padding:8px 10px;font-size:13px"><b>INV-2026-0012</b><br><span style="color:#8A94A6;font-size:11px">Rahim Steel · Banani Commercial Tower</span></td><td style="padding:8px 10px;font-size:13px">2026-06</td><td style="padding:8px 10px;font-size:13px;text-align:right">৳4,50,000</td></tr>'];
        case 'rent_reminder': return ['tenant_name' => 'Sultana Rahman', 'invoice_id' => 'INV-2026-0011', 'month' => '2026-06', 'amount' => '32,000', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)'];
        case 'invoice': return ['tenant_name' => 'Sultana Rahman', 'invoice_id' => 'INV-2026-0011', 'month' => '2026-06', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)', 'amount' => '32,000', 'due' => '32,000', 'due_color' => '#B91C1C'];
        case 'receipt': return ['tenant_name' => 'Sultana Rahman', 'receipt_id' => 'PAY-010', 'date' => '02 Aug 2026', 'amount' => '25,000', 'amount_words_en' => 'Twenty-Five Thousand', 'amount_words_bn' => 'পঁচিশ হাজার টাকা মাত্র', 'method' => 'bKash', 'ref' => '8T5XK2QZ', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)', 'month' => '2026-06'];
        case 'renewal_status': return ['tenant_name' => 'Sultana Rahman', 'property' => 'Dhanmondi Apartment', 'unit' => 'Apartment 7B (U-010)', 'lease' => 'L-007', 'status' => 'Approved', 'new_end' => '14 Dec 2027', 'new_rent' => '42,000', 'note' => 'Thank you for being a valued tenant.'];
    }
    return [];
}

