function seed_email_tpl($id) {
    $tpls = [
'otp' => [
'Your KRTaker verification code: {{code}}',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">KRTaker<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <h1 style="margin:0 0 8px;font-size:20px;color:#101828">Verify your email</h1>
    <p style="margin:0 0 22px;color:#475467;font-size:14px;line-height:1.6">Hi {{name}}, use the one-time code below to activate your KRTaker workspace.</p>
    <div style="border:2px dashed #2F80ED;background:#F6F9FE;border-radius:14px;padding:20px 14px;text-align:center;font-size:34px;font-weight:800;color:#2F80ED;letter-spacing:10px;padding-left:24px">{{code}}</div>
    <p style="margin:20px 0 0;color:#667085;font-size:12.5px;line-height:1.8">⏱ The code expires in {{expiry}}.<br>🔒 Never share this code. KRTaker will never ask for your password or OTP over the phone.</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">
    KRTaker · Dhaka, Bangladesh<br>support@krtaker.com · +880 1722-759646<br>If you did not request this code, ignore this email — your account is safe.
  </div>
</div>
HTML,
],
'welcome' => [
'Welcome to KRTaker 🎉 — your trial is live',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">KRTaker<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <h1 style="margin:0 0 8px;font-size:20px;color:#101828">Welcome aboard, {{name}} 🎉</h1>
    <p style="margin:0 0 8px;color:#475467;font-size:14px;line-height:1.7">Your KRTaker workspace is active on a <b>14-day free trial</b> until <b>{{trial_end}}</b> — no card required.</p>
    <p style="margin:0 0 22px;color:#475467;font-size:14px;line-height:1.7">Add your first property, invite your team, and let KR — your AI caretaker — handle rent, receipts, TDS and compliance.</p>
    <a href="{{workspace_url}}" style="display:inline-block;background:#2F80ED;color:#fff;padding:13px 28px;border-radius:12px;text-decoration:none;font-weight:700;font-size:14px">Open your workspace →</a>
    <p style="margin:22px 0 0;color:#8A94A6;font-size:12.5px;line-height:1.7">Questions? Reply to this email — we reply within 24 hours. 🇧🇩 Built for Bangladeshi property owners.</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh<br>support@krtaker.com · +880 1722-759646</div>
</div>
HTML,
],
'collections' => [
'KRTaker — {{unpaid}} unpaid rent invoice(s)',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#E67E22,#D35400);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">Overdue collections<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <p style="margin:0 0 6px;color:#475467;font-size:14px"><b>{{unpaid}}</b> unpaid invoice(s) · <b>৳{{total}}</b> outstanding</p>
    <table style="width:100%;border-collapse:collapse;margin-top:14px">{{items}}</table>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com<br>This digest is generated by KR, your AI caretaker.</div>
</div>
HTML,
],
'rent_reminder' => [
'Rent reminder — {{invoice_id}} ({{month}})',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">Rent reminder<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <p style="margin:0 0 14px;color:#475467;font-size:14px">Dear {{tenant_name}},</p>
    <p style="margin:0 0 14px;color:#475467;font-size:14px;line-height:1.7">Invoice <b>{{invoice_id}}</b> for <b>{{month}}</b> — <b>৳{{amount}}</b> — is due for <b>{{property}}</b> ({{unit}}).</p>
    <div style="background:#FFF4E5;border:1px solid #FFD9A0;border-radius:12px;padding:14px 18px;font-size:13px;color:#7A4A00;margin-bottom:16px">⚠️ <b>Tier {{tier}} reminder</b> · {{days_overdue}} day(s) past due — {{tier_note}}</div>
    <div style="margin:0 0 16px"><a href="{{pay_url}}" style="display:inline-block;background:#2F80ED;color:#ffffff;padding:13px 26px;border-radius:10px;font-size:14px;font-weight:700;text-decoration:none">💳 Pay now — ৳{{amount}}</a></div>
    <div style="background:#F6F9FE;border:1px solid #E4EAF3;border-radius:12px;padding:14px 18px;font-size:13px;color:#1A2433;margin-bottom:18px">Prefer bKash, Nagad or your KRTaker tenant portal? The button takes you straight to the secure checkout for invoice <b>{{invoice_id}}</b>. {{late_fee}}</div>
    <p style="margin:0;color:#8A94A6;font-size:12.5px">— KRTaker, your AI caretaker 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'invoice' => [
'Your rent invoice {{invoice_id}} ({{month}}) — KRTaker',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">Rent invoice<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <p style="margin:0 0 16px;color:#475467;font-size:14px">Dear {{tenant_name}},</p>
    <div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Invoice</span><b>{{invoice_id}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Month</span><b>{{month}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Property</span><b>{{property}} ({{unit}})</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Amount</span><b>৳{{amount}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:14px 18px;background:#F6F9FE;font-size:14px"><span style="color:#8A94A6;font-weight:600">Balance due</span><b style="color:{{due_color}};font-size:16px">৳{{due}}</b></div>
    </div>
    <p style="margin:0 0 16px;color:#475467;font-size:13.5px;line-height:1.7">Pay via bKash, Nagad or SSLCommerz — the button takes you straight to the secure checkout for invoice <b>{{invoice_id}}</b>. A printable copy is available inside your KRTaker dashboard.</p>
    <div style="margin:0 0 16px"><a href="{{pay_url}}" style="display:inline-block;background:#2F80ED;color:#ffffff;padding:13px 26px;border-radius:10px;font-size:14px;font-weight:700;text-decoration:none">💳 Pay now — ৳{{due}}</a></div>
    <p style="margin:0;color:#8A94A6;font-size:12.5px">— KRTaker, your AI caretaker 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'receipt' => [
'Payment receipt {{receipt_id}} — KRTaker',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#27AE60,#1E8449);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">Payment received ✓<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <p style="margin:0 0 16px;color:#475467;font-size:14px">Dear {{tenant_name}}, thank you for your payment.</p>
    <div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Receipt</span><b>{{receipt_id}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Date</span><b>{{date}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Amount</span><b style="font-size:16px">৳{{amount}}</b></div>
      <div style="padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:12.5px;color:#475467;line-height:1.7"><span style="color:#8A94A6">In words:</span><br>{{amount_words_en}}<br>{{amount_words_bn}}</div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Method</span><b>{{method}} {{ref}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;font-size:13px"><span style="color:#8A94A6">For</span><b>{{property}} ({{unit}}) · {{month}}</b></div>
    </div>
    <p style="margin:0;color:#8A94A6;font-size:12.5px;line-height:1.7">Keep this email for your records — it is your official money receipt. — KRTaker, your AI caretaker 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'renewal_status' => [
'Your lease renewal {{status}} — {{property}} ({{lease}})',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">Lease renewal {{status}}<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <p style="margin:0 0 16px;color:#475467;font-size:14px">Dear {{tenant_name}},</p>
    <div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Property</span><b>{{property}} ({{unit}})</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Lease</span><b>{{lease}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Status</span><b style="color:{{status_color}}">{{status}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">New end date</span><b>{{new_end}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:14px 18px;background:#F6F9FE;font-size:14px"><span style="color:#8A94A6;font-weight:600">Monthly rent</span><b>৳{{new_rent}}</b></div>
    </div>
    <p style="margin:0 0 18px;color:#475467;font-size:13.5px;line-height:1.7">{{note}}</p>
    <p style="margin:0;color:#8A94A6;font-size:12.5px">Any questions? Reply to this email — we reply within 24 hours. — KRTaker, your AI caretaker 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'premium_welcome' => [
'👑 Your {{tier_label}} is active — your AI caretaker is on duty',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#8E2DE2,#4A00E0);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">👑 {{tier_label}}<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · REMOTE CARETAKER</span></div>
  </div>
  <div style="padding:32px">
    <h1 style="margin:0 0 8px;font-size:20px;color:#101828">Your caretaker is on duty, {{name}}</h1>
    <p style="margin:0 0 18px;color:#475467;font-size:14px;line-height:1.7">Your <b>{{tier_label}}</b> subscription for <b>{{property}}</b> is live. KR will now chase rent, settle utility bills, coordinate repairs and keep you posted.</p>
    <div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Plan</span><b>{{tier_label}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Property under care</span><b>{{property}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Billing</span><b>{{cycle}} · {{price}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:14px 18px;background:#F6F9FE;font-size:14px"><span style="color:#8A94A6;font-weight:600">Next invoice</span><b>{{next_invoice}}</b></div>
    </div>
    <a href="{{workspace_url}}" style="display:inline-block;background:#2F80ED;color:#fff;padding:13px 28px;border-radius:12px;text-decoration:none;font-weight:700;font-size:14px">Open caretaker dashboard →</a>
    <p style="margin:22px 0 0;color:#8A94A6;font-size:12.5px;line-height:1.7">Questions? Reply to this email — your concierge line replies within 24 hours. 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'move_out' => [
'Move-out completed — {{property}} · {{unit_name}} · {{status}}',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#101828,#344054);padding:22px 32px">
    <div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">🚪 Move-out completed<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
  </div>
  <div style="padding:32px">
    <h1 style="margin:0 0 8px;font-size:20px;color:#101828">Settlement statement, {{name}}</h1>
    <p style="margin:0 0 18px;color:#475467;font-size:14px;line-height:1.7">Your tenancy at <b>{{property}}</b> — <b>{{unit_name}}</b> was formally closed on <b>{{move_out_date}}</b>. The final settlement is attached below.</p>
    <div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Lease</span><b>{{lease}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Rent arrears</span><b>৳{{rent_due}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Utility dues</span><b>৳{{util_due}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Damage deductions</span><b>৳{{dmg_due}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">Advance deposit</span><b>৳{{deposit}}</b></div>
      <div style="display:flex;justify-content:space-between;padding:14px 18px;background:#F6F9FE;font-size:14px"><span style="color:#8A94A6;font-weight:600">Final balance</span><b style="color:{{status_color}}">৳{{balance}} · {{status}}</b></div>
    </div>
    <a href="{{workspace_url}}" style="display:inline-block;background:#2F80ED;color:#fff;padding:13px 28px;border-radius:12px;text-decoration:none;font-weight:700;font-size:14px">View settlement certificate →</a>
    <p style="margin:22px 0 0;color:#8A94A6;font-size:12.5px;line-height:1.7">The deposit refund (if any) is processed within 5 working days. Thank you for renting with KRTaker. 🇧🇩</p>
  </div>
  <div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
  </div>
HTML,
],
'welcome_bn' => [
'KRTaker-এ স্বাগতম 🎉 — আপনার ট্রায়াল শুরু হইল',
<<<'HTML'
<div style="font-family:Inter,'Hind Siliguri',Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
<div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
<div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">KRTaker<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KEY RESPONSIBILITY TAKER</span></div>
</div>
<div style="padding:32px">
<h1 style="margin:0 0 8px;font-size:20px;color:#101828">স্বাগতম, {{name}} 🎉</h1>
<p style="margin:0 0 8px;color:#475467;font-size:14px;line-height:1.7">আপনার KRTaker ওয়ার্কস্পেস <b>{{trial_end}}</b> পর্যন্ত <b>১৪ দিনের ফ্রি ট্রায়ালে</b> সক্রিয় — কোনো কার্ড প্রয়োজন নেই।</p>
<p style="margin:0 0 22px;color:#475467;font-size:14px;line-height:1.7">আপনার প্রথম সম্পত্তি যোগ করুন, আপনার টিমকে আমন্ত্রণ জানান এবং KR — আপনার AI কেয়ারটেকার — কে ভাড়া, রসিদ, টিডিএস ও কমপ্লায়েন্স সামলাতে দিন।</p>
<a href="{{workspace_url}}" style="display:inline-block;background:#2F80ED;color:#fff;padding:13px 28px;border-radius:12px;text-decoration:none;font-weight:700;font-size:14px">ওয়ার্কস্পেস খুলুন →</a>
<p style="margin:22px 0 0;color:#8A94A6;font-size:12.5px;line-height:1.7">প্রশ্ন আছে? এই ইমেইলের উত্তর দিন — আমরা ২৪ ঘণ্টার মধ্যে উত্তর দিই। 🇧🇩 বাংলাদেশের সম্পত্তি মালিকদের জন্য তৈরি।</p>
</div>
<div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh<br>support@krtaker.com · +880 1722-759646</div>
</div>
HTML,
],
'rent_reminder_bn' => [
'ভাড়া অনুস্মারক — {{invoice_id}} ({{month}})',
<<<'HTML'
<div style="font-family:Inter,'Hind Siliguri',Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
<div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
<div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">ভাড়া অনুস্মারক<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
</div>
<div style="padding:32px">
<p style="margin:0 0 14px;color:#475467;font-size:14px">প্রিয় {{tenant_name}},</p>
<p style="margin:0 0 14px;color:#475467;font-size:14px;line-height:1.7"><b>{{property}}</b> ({{unit}}) এর জন্য <b>{{month}}</b> মাসের ইনভয়েস <b>{{invoice_id}}</b> — <b>৳{{amount}}</b> — পরিশোধযোগ্য।</p>
<div style="background:#FFF4E5;border:1px solid #FFD9A0;border-radius:12px;padding:14px 18px;font-size:13px;color:#7A4A00;margin-bottom:16px">⚠️ <b>Tier {{tier}} অনুস্মারক</b> · {{days_overdue}} দিন অতিবাহিত — {{tier_note}}</div>
<div style="margin:0 0 16px"><a href="{{pay_url}}" style="display:inline-block;background:#2F80ED;color:#ffffff;padding:13px 26px;border-radius:10px;font-size:14px;font-weight:700;text-decoration:none">💳 এখনই পরিশোধ করুন — ৳{{amount}}</a></div>
<div style="background:#F6F9FE;border:1px solid #E4EAF3;border-radius:12px;padding:14px 18px;font-size:13px;color:#1A2433;margin-bottom:18px">bKash, Nagad অথবা KRTaker টেন্যান্ট পোর্টাল ব্যবহার করতে চান? বাটনটি আপনাকে ইনভয়েস <b>{{invoice_id}}</b> এর নিরাপদ চেকআউটে নিয়ে যাবে। {{late_fee}}</div>
<p style="margin:0;color:#8A94A6;font-size:12.5px">— KRTaker, আপনার AI কেয়ারটেকার 🇧🇩</p>
</div>
<div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'invoice_bn' => [
'আপনার ভাড়ার ইনভয়েস {{invoice_id}} ({{month}}) — KRTaker',
<<<'HTML'
<div style="font-family:Inter,'Hind Siliguri',Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
<div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
<div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">ভাড়ার ইনভয়েস<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
</div>
<div style="padding:32px">
<p style="margin:0 0 16px;color:#475467;font-size:14px">প্রিয় {{tenant_name}},</p>
<div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">ইনভয়েস</span><b>{{invoice_id}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">মাস</span><b>{{month}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">সম্পত্তি</span><b>{{property}} ({{unit}})</b></div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">পরিমাণ</span><b>৳{{amount}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:14px 18px;background:#F6F9FE;font-size:14px"><span style="color:#8A94A6;font-weight:600">বকেয়া</span><b style="color:{{due_color}};font-size:16px">৳{{due}}</b></div>
</div>
<p style="margin:0 0 16px;color:#475467;font-size:13.5px;line-height:1.7">bKash, Nagad অথবা SSLCommerz-এ পরিশোধ করুন — বাটনটি ইনভয়েস <b>{{invoice_id}}</b> এর নিরাপদ চেকআউটে নিয়ে যাবে। প্রিন্টযোগ্য কপি আপনার KRTaker ড্যাশবোর্ডে পাওয়া যাবে।</p>
<div style="margin:0 0 16px"><a href="{{pay_url}}" style="display:inline-block;background:#2F80ED;color:#ffffff;padding:13px 26px;border-radius:10px;font-size:14px;font-weight:700;text-decoration:none">💳 এখনই পরিশোধ করুন — ৳{{due}}</a></div>
<p style="margin:0;color:#8A94A6;font-size:12.5px">— KRTaker, আপনার AI কেয়ারটেকার 🇧🇩</p>
</div>
<div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'receipt_bn' => [
'পেমেন্ট রসিদ {{receipt_id}} — KRTaker',
<<<'HTML'
<div style="font-family:Inter,'Hind Siliguri',Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
<div style="background:linear-gradient(135deg,#27AE60,#1E8449);padding:22px 32px">
<div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">পেমেন্ট গৃহীত ✓<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
</div>
<div style="padding:32px">
<p style="margin:0 0 16px;color:#475467;font-size:14px">প্রিয় {{tenant_name}}, আপনার পেমেন্টের জন্য ধন্যবাদ।</p>
<div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">রসিদ</span><b>{{receipt_id}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">তারিখ</span><b>{{date}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">পরিমাণ</span><b style="font-size:16px">৳{{amount}}</b></div>
  <div style="padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:12.5px;color:#475467;line-height:1.7"><span style="color:#8A94A6">কথায়:</span><br>{{amount_words_en}}<br>{{amount_words_bn}}</div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">মাধ্যম</span><b>{{method}} {{ref}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;font-size:13px"><span style="color:#8A94A6">বিষয়</span><b>{{property}} ({{unit}}) · {{month}}</b></div>
</div>
<p style="margin:0;color:#8A94A6;font-size:12.5px;line-height:1.7">রেকর্ডের জন্য এই ইমেইলটি সংরক্ষণ করুন — এটি আপনার আনুষ্ঠানিক টাকা প্রাপ্তি রসিদ। — KRTaker, আপনার AI কেয়ারটেকার 🇧🇩</p>
</div>
<div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'move_out_bn' => [
'চুক্তি শেষ — {{property}} · {{unit_name}} · {{status}}',
<<<'HTML'
<div style="font-family:Inter,'Hind Siliguri',Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
<div style="background:linear-gradient(135deg,#101828,#344054);padding:22px 32px">
<div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">🚪 চুক্তি সম্পন্ন<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
</div>
<div style="padding:32px">
<h1 style="margin:0 0 8px;font-size:20px;color:#101828">নিষ্পত্তি বিবরণী, {{name}}</h1>
<p style="margin:0 0 18px;color:#475467;font-size:14px;line-height:1.7"><b>{{property}}</b> — <b>{{unit_name}}</b> এ আপনার ভাড়া <b>{{move_out_date}}</b> তারিখে আনুষ্ঠানিকভাবে সমাপ্ত হইয়াছে। চূড়ান্ত নিষ্পত্তি নিম্নে দেওয়া হইল।</p>
<div style="border:1px solid #E4EAF3;border-radius:14px;overflow:hidden;margin-bottom:18px">
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">চুক্তি</span><b>{{lease}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">ভাড়া বকেয়া</span><b>৳{{rent_due}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">ইউটিলিটি বকেয়া</span><b>৳{{util_due}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">ক্ষতিপূরণ কর্তন</span><b>৳{{dmg_due}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:12px 18px;border-bottom:1px solid #E4EAF3;font-size:13px"><span style="color:#8A94A6">অগ্রিম জামানত</span><b>৳{{deposit}}</b></div>
  <div style="display:flex;justify-content:space-between;padding:14px 18px;background:#F6F9FE;font-size:14px"><span style="color:#8A94A6;font-weight:600">চূড়ান্ত ব্যালেন্স</span><b style="color:{{status_color}}">৳{{balance}} · {{status}}</b></div>
</div>
<a href="{{workspace_url}}" style="display:inline-block;background:#2F80ED;color:#fff;padding:13px 28px;border-radius:12px;text-decoration:none;font-weight:700;font-size:14px">নিষ্পত্তি সনদ দেখুন →</a>
<p style="margin:22px 0 0;color:#8A94A6;font-size:12.5px;line-height:1.7">জামানত ফেরত (যদি থাকে) ৫ কর্মদিবসের মধ্যে প্রক্রিয়া করা হয়। KRTaker-এ ভাড়া নেওয়ার জন্য ধন্যবাদ। 🇧🇩</p>
</div>
<div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'arrears' => [
'⚠️ Arrears notice — {{invoice_id}} ({{month}})',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
<div style="background:linear-gradient(135deg,#E74C3C,#B03A2E);padding:22px 32px">
<div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">⚠️ Arrears notice<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
</div>
<div style="padding:32px">
<p style="margin:0 0 14px;color:#475467;font-size:14px">Dear {{tenant_name}},</p>
<p style="margin:0 0 14px;color:#475467;font-size:14px;line-height:1.7">Invoice <b>{{invoice_id}}</b> for <b>{{month}}</b> — <b>৳{{amount}}</b> — for <b>{{property}}</b> ({{unit}}) remains <b>unpaid</b>. As of today your total outstanding is <b>৳{{total_due}}</b>, including <b>{{days_overdue}} day(s)</b> of arrears.</p>
<div style="background:#FDECEA;border:1px solid #F5C6C0;border-radius:12px;padding:14px 18px;font-size:13px;color:#7F1D1D;margin-bottom:16px">Kindly settle the balance within <b>7 days</b>. Continued non-payment may result in late fees and, ultimately, termination proceedings under the Premises Rent Control Act, 1991.</div>
<div style="margin:0 0 16px"><a href="{{pay_url}}" style="display:inline-block;background:#E74C3C;color:#ffffff;padding:13px 26px;border-radius:10px;font-size:14px;font-weight:700;text-decoration:none">💳 Pay now — ৳{{amount}}</a></div>
<p style="margin:0;color:#8A94A6;font-size:12.5px">— KRTaker, your AI caretaker 🇧🇩</p>
</div>
<div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
'owner_statement' => [
'📊 Owner Statement — {{property}} ({{month_label}})',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
<div style="background:linear-gradient(135deg,#2F80ED,#1E5EB8);padding:22px 32px">
<div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">📊 Monthly Owner Statement<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">{{org_name}} · KRTaker</span></div>
</div>
<div style="padding:32px">
<p style="margin:0 0 6px;color:#475467;font-size:14px">Dear {{owner_name}},</p>
<p style="margin:0 0 20px;color:#475467;font-size:14px">Here is your statement for <b>{{property}}</b> — <b>{{month_label}}</b>.</p>
<table style="border-collapse:collapse;width:100%;font-size:13.5px">
<tr><td style="padding:9px 10px;border-bottom:1px solid #E4EAF3;color:#667085">Gross rent billed</td><td style="padding:9px 10px;border-bottom:1px solid #E4EAF3;text-align:right;font-weight:700">৳{{gross}}</td></tr>
<tr><td style="padding:9px 10px;border-bottom:1px solid #E4EAF3;color:#667085">Collected</td><td style="padding:9px 10px;border-bottom:1px solid #E4EAF3;text-align:right;font-weight:700;color:#12a150">৳{{collected}}</td></tr>
<tr><td style="padding:9px 10px;border-bottom:1px solid #E4EAF3;color:#667085">TDS deducted</td><td style="padding:9px 10px;border-bottom:1px solid #E4EAF3;text-align:right;color:#B91C1C">− ৳{{tds}}</td></tr>
<tr><td style="padding:9px 10px;border-bottom:1px solid #E4EAF3;color:#667085">Service charge</td><td style="padding:9px 10px;border-bottom:1px solid #E4EAF3;text-align:right;color:#B91C1C">− ৳{{service}}</td></tr>
<tr><td style="padding:9px 10px;border-bottom:1px solid #E4EAF3;color:#667085">Expenses</td><td style="padding:9px 10px;border-bottom:1px solid #E4EAF3;text-align:right;color:#B91C1C">− ৳{{expenses}}</td></tr>
<tr><td style="padding:11px 10px;font-weight:800;font-size:14px">Net payable</td><td style="padding:11px 10px;text-align:right;font-weight:800;font-size:15px;color:#2F80ED">৳{{net}}</td></tr>
</table>
<p style="margin:18px 0 4px;font-size:12px;color:#8A94A6">Collection rate: <b>{{collect_rate}}%</b> · {{paid_invoices}} of {{total_invoices}} invoices paid</p>
<p style="margin:0 0 18px;font-size:12px;color:#8A94A6">{{payout_line}}</p>
<p style="margin:0 0 6px;font-size:12.5px;color:#667085">You can view the full statement with line items in your dashboard.</p>
<p style="margin:0"><a href="{{dashboard_url}}" style="display:inline-block;background:#2F80ED;color:#fff;text-decoration:none;padding:11px 22px;border-radius:10px;font-size:13.5px;font-weight:700">Open dashboard →</a></p>
</div>
<div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">{{org_name}} · {{org_address}}<br>{{org_email}} · {{org_phone}}</div>
</div>
HTML,
],
'notice_email' => [
'📢 {{notice_title}} — {{org_name}}',
<<<'HTML'
<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
<div style="background:linear-gradient(135deg,#F59E0B,#B45309);padding:22px 32px">
<div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">📢 Notice<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">{{org_name}} · KRTaker</span></div>
</div>
<div style="padding:32px">
<p style="margin:0 0 14px;color:#475467;font-size:14px">Dear {{tenant_name}},</p>
<div style="background:#FFF8E7;border:1px solid #F5D78E;border-radius:14px;padding:18px 20px;margin-bottom:16px">
<div style="font-size:16px;font-weight:800;color:#101828;margin-bottom:8px">{{notice_title}}</div>
<div style="font-size:13.5px;color:#475467;line-height:1.75">{{notice_body}}</div>
</div>
<p style="margin:0 0 4px;font-size:12px;color:#8A94A6">Posted by {{author}} · {{posted_date}}</p>
<p style="margin:0 0 16px;font-size:12px;color:#8A94A6">You can view the tenant board in your portal.</p>
<p style="margin:0"><a href="{{portal_url}}" style="display:inline-block;background:#2F80ED;color:#fff;text-decoration:none;padding:11px 22px;border-radius:10px;font-size:13.5px;font-weight:700">Open portal →</a></p>
</div>
<div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">{{org_name}} · {{org_address}}<br>{{org_email}} · {{org_phone}}</div>
</div>
HTML,
],
'arrears_bn' => [
'⚠️ বকেয়া নোটিশ — {{invoice_id}} ({{month}})',
<<<'HTML'
<div style="font-family:Inter,'Hind Siliguri',Arial,sans-serif;max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #E4EAF3;border-radius:16px;overflow:hidden">
<div style="background:linear-gradient(135deg,#E74C3C,#B03A2E);padding:22px 32px">
<div style="font-size:19px;font-weight:800;color:#fff;letter-spacing:-.3px">⚠️ বকেয়া নোটিশ<span style="display:block;font-size:10.5px;font-weight:600;letter-spacing:2.4px;opacity:.8;margin-top:2px">KRTaker · KEY RESPONSIBILITY TAKER</span></div>
</div>
<div style="padding:32px">
<p style="margin:0 0 14px;color:#475467;font-size:14px">প্রিয় {{tenant_name}},</p>
<p style="margin:0 0 14px;color:#475467;font-size:14px;line-height:1.7"><b>{{property}}</b> ({{unit}}) এর জন্য <b>{{month}}</b> মাসের ইনভয়েস <b>{{invoice_id}}</b> — <b>৳{{amount}}</b> — এখনও <b>অপরিশোধিত</b>। আজ পর্যন্ত আপনার মোট বকেয়া <b>৳{{total_due}}</b> টাকা, যাহাতে {{days_overdue}} দিনের বকেয়া অন্তর্ভুক্ত।</p>
<div style="background:#FDECEA;border:1px solid #F5C6C0;border-radius:12px;padding:14px 18px;font-size:13px;color:#7F1D1D;margin-bottom:16px">অনুরোধ করা যাচ্ছে, <b>৭ দিনের</b> মধ্যে বকেয়া পরিশোধ করুন। অবিরত অনাপয়মেন্টের ক্ষেত্রে ১৯৯১ সনের ভাড়া নিয়ন্ত্রণ আইন অনুযায়ী বিলম্ব ফি এবং সর্বশেষে চুক্তি বাতিলের পদক্ষেপ গ্রহণ করা হইবে।</div>
<div style="margin:0 0 16px"><a href="{{pay_url}}" style="display:inline-block;background:#E74C3C;color:#ffffff;padding:13px 26px;border-radius:10px;font-size:14px;font-weight:700;text-decoration:none">💳 এখনই পরিশোধ করুন — ৳{{amount}}</a></div>
<p style="margin:0;color:#8A94A6;font-size:12.5px">— KRTaker, আপনার AI কেয়ারটেকার 🇧🇩</p>
</div>
<div style="background:#F8FAFD;border-top:1px solid #E4EAF3;padding:18px 32px;font-size:11.5px;color:#8A94A6;line-height:1.9">KRTaker · Dhaka, Bangladesh · support@krtaker.com</div>
</div>
HTML,
],
];
return $tpls[$id] ?? ['', ''];
}
function seed_templates($pdo) {
    $names = [
        'LSE-STD' => ['lease', 'Standard Tenancy Agreement', 'Tenancy Agreement', 'en'],
        'LSE-BN' => ['lease', 'ভাড়া চুক্তি (Bengali Tenancy Agreement)', 'ভাড়া চুক্তি', 'bn'],
        'SRV-STD' => ['service', 'Standard Service Contract', 'Service Contract', 'en'],
        'SRV-BN' => ['service', 'সার্ভিস চুক্তি (Bengali Service Contract)', 'সার্ভিস চুক্তি', 'bn'],
        'RCP-RENT' => ['receipt', 'Rent Receipt', 'Money Receipt — Rent', 'en'],
        'RCP-ADV' => ['receipt', 'Advance / Security Deposit Receipt', 'Money Receipt — Advance', 'en'],
        'RCP-SVC' => ['receipt', 'Service Charge Receipt', 'Money Receipt — Service Charges', 'en'],
        'RCP-GEN' => ['receipt', 'General Payment Receipt', 'Money Receipt — Payment Received', 'en'],
        'RCP-BN' => ['receipt', 'টাকা প্রাপ্তি রসিদ (Bengali Money Receipt)', 'টাকা প্রাপ্তি রসিদ', 'bn'],
        'NTC-ARR' => ['lease', 'Arrears / Dunning Notice', 'Notice of Arrears', 'en'],
        'NTC-ARR-BN' => ['lease', 'বকেয়া ভাড়া নোটিশ (Arrears Notice)', 'বকেয়া ভাড়া সংক্রান্ত নোটিশ', 'bn'],
        'NTC-MOVE' => ['lease', 'Move-out / Vacation Notice', 'Notice of Move-out', 'en'],
        'NTC-MOVE-BN' => ['lease', 'খালি করার নোটিশ (Move-out Notice)', 'খালি করার নোটিশ', 'bn'],
        'NTC-UTIL' => ['lease', 'Utility / Service Charge Notice', 'Notice of Utility Charges', 'en'],
        'NTC-UTIL-BN' => ['lease', 'ইউটিলিটি/সার্ভিস চার্জ নোটিশ', 'ইউটিলিটি/সার্ভিস চার্জ নোটিশ', 'bn'],
        'WRK-ORD' => ['service', 'Work Order', 'Work Order', 'en'],
        'WRK-ORD-BN' => ['service', 'ওয়ার্ক অর্ডার (Work Order)', 'ওয়ার্ক অর্ডার', 'bn'],
        'NOC-STD' => ['lease', 'No Objection Certificate (NOC)', 'No Objection Certificate', 'en'],
        'NOC-BN' => ['lease', 'আপত্তি-মুক্ত সনদ (NOC)', 'আপত্তি-মুক্ত সনদ', 'bn'],
    ];
    foreach ($names as $id => $n) {
        $body = seed_tpl_body($id);
        $st = $pdo->prepare('SELECT COUNT(*) FROM doc_templates WHERE id=?'); $st->execute([$id]);
        if (!(int)$st->fetchColumn()) {
            $pdo->prepare('INSERT INTO doc_templates (id,kind,name,title,body,is_default,updated_by,lang) VALUES (?,?,?,?,?,1,?,?)')
                ->execute([$id, $n[0], $n[1], $n[2], $body, 'system', $n[3]]);
        }
    }
    $emails = ['otp' => ['Verification (OTP) Email', 'en'], 'welcome' => ['Welcome Email', 'en'], 'welcome_bn' => ['স্বাগতম ইমেইল (Bengali Welcome)', 'bn'], 'collections' => ['Collections Digest', 'en'], 'rent_reminder' => ['Rent Reminder', 'en'], 'rent_reminder_bn' => ['ভাড়া অনুস্মারক (Bengali Rent Reminder)', 'bn'], 'invoice' => ['Invoice Email', 'en'], 'invoice_bn' => ['ভাড়ার ইনভয়েস (Bengali Invoice)', 'bn'], 'receipt' => ['Receipt Email', 'en'], 'receipt_bn' => ['পেমেন্ট রসিদ (Bengali Receipt)', 'bn'], 'renewal_status' => ['Lease Renewal Status', 'en'], 'premium_welcome' => ['Caretaker Subscription Confirmation', 'en'], 'move_out' => ['Move-out / Settlement Notice', 'en'], 'move_out_bn' => ['চুক্তি শেষ নোটিশ (Bengali Move-out)', 'bn'], 'arrears' => ['Arrears Notice Email', 'en'], 'arrears_bn' => ['বকেয়া নোটিশ ইমেইল (Bengali Arrears)', 'bn'], 'owner_statement' => ['Monthly Owner Statement', 'en'], 'notice_email' => ['Notice Broadcast Email', 'en']];
    foreach ($emails as $id => $em) {
        list($subj, $body) = seed_email_tpl($id);
        $st = $pdo->prepare('SELECT COUNT(*) FROM email_templates WHERE id=?'); $st->execute([$id]);
        if (!(int)$st->fetchColumn()) {
            $pdo->prepare('INSERT INTO email_templates (id,name,subject,body,updated_by,lang) VALUES (?,?,?,?,?,?)')
                ->execute([$id, $em[0], $subj, $body, 'system', $em[1]]);
        }
    }
    /* Phase 15: refresh stock rent_reminder template with tier placeholders (only when not customized) */
    $st = $pdo->prepare("SELECT body FROM email_templates WHERE id='rent_reminder'"); $st->execute();
    $rr = $st->fetchColumn();
    if ($rr !== false && strpos($rr, '{{tier_note}}') === false) {
        list($s2, $b2) = seed_email_tpl('rent_reminder');
        $pdo->prepare("UPDATE email_templates SET subject=?, body=?, updated_by='system' WHERE id='rent_reminder'")->execute([$s2, $b2]);
    }
}
function email_render($id, $vars) {
    $pdo = db();
    $st = $pdo->prepare('SELECT * FROM email_templates WHERE id=?'); $st->execute([$id]);
    $t = $st->fetch(PDO::FETCH_ASSOC);
    if ($t) { $subj = $t['subject']; $body = $t['body']; }
    else { list($subj, $body) = seed_email_tpl($id); }
    return [render_merge($subj, $vars), render_merge($body, $vars)];
}
function org_vars($u) {
    $pdo = db();
    $m = [];
    foreach ($pdo->query("SELECT k,v FROM platform_meta WHERE k LIKE 'org\\_%' ESCAPE '\\'") as $r) $m[$r['k']] = $r['v'];
    return [
        'org_name'    => esc($m['org_name'] ?? (($u['org'] ?? '') ?: ($u['name'] ?? 'KRTaker'))),
        'org_phone'   => esc($m['org_phone'] ?? ($u['phone'] ?? '')),
        'org_email'   => esc($m['org_email'] ?? ($u['email'] ?? 'support@krtaker.com')),
        'org_address' => esc($m['org_address'] ?? 'Dhaka, Bangladesh'),
        'today'       => gmdate('d M Y'),
    ];
}
function tpl_vars_for($u, $kind, $ref) {
    $pdo = db();
    $vars = org_vars($u);
    $links = [];
    if ($kind === 'lease') {
        $st = $pdo->prepare('SELECT l.id AS lid, l.u AS uid, l.t AS tid, l.start, l.end, l.rent, l.adv, l.res, l.reg_office, l.reg_deed,
                             u.name AS uname, u.floor, u.p AS pid, p.name AS pname, p.jur, p.holding,
                             t.name AS tname, t.phone AS tphone, t.email AS temail, t.nid AS tnid
                             FROM leases l JOIN units u ON u.id=l.u JOIN properties p ON p.id=u.p JOIN tenants t ON t.id=l.t WHERE l.id=?');
        $st->execute([$ref]); $r = $st->fetch(PDO::FETCH_ASSOC);
        if (!$r) return null;
        $res = ((int)($r['res'] ?? 1)) === 1;
        $vars += [
            'lease_id' => esc($r['lid']), 'lease_start' => esc($r['start']), 'lease_end' => esc($r['end']),
            'rent' => money_bd((int)$r['rent']), 'rent_words' => num_to_words_en((int)$r['rent']), 'rent_words_bn' => num_to_words_bn((int)$r['rent']) . ' টাকা',
            'advance' => money_bd((int)$r['adv']), 'advance_words' => num_to_words_en((int)$r['adv']), 'advance_words_bn' => num_to_words_bn((int)$r['adv']) . ' টাকা',
            'reg_office' => esc($r['reg_office']), 'reg_deed' => esc($r['reg_deed']),
            'reg_note' => $res
                ? 'Rent is within the TPA 1882 §107 exemption — compulsory registration is not required, but registration is recommended for enforceability.'
                : 'This lease exceeds the TPA 1882 §107 exemption — it MUST be registered at the Sub-Registrar\'s office to be enforceable.',
            'tenant_name' => esc($r['tname']), 'tenant_phone' => esc($r['tphone']), 'tenant_nid' => esc($r['tnid']), 'tenant_email' => esc($r['temail']),
            'property_name' => esc($r['pname']), 'property_address' => esc(trim(trim($r['holding'] . ', ' . $r['jur']), ' ,')),
            'unit_name' => esc($r['uname']), 'unit_id' => esc($r['uid']), 'floor' => esc($r['floor']),
        ];
        $links = [
            'tenant_name' => ['tenants', $r['tid'], '👤'], 'tenant_phone' => ['tenants', $r['tid'], '👤'], 'tenant_nid' => ['tenants', $r['tid'], '👤'], 'tenant_email' => ['tenants', $r['tid'], '👤'],
            'property_name' => ['properties', $r['pid'], '🏢'], 'property_address' => ['properties', $r['pid'], '🏢'],
            'unit_name' => ['units', $r['uid'], '🚪'], 'unit_id' => ['units', $r['uid'], '🚪'], 'floor' => ['units', $r['uid'], '🚪'],
            'lease_id' => ['leases', $r['lid'], '📄'], 'lease_start' => ['leases', $r['lid'], '📄'], 'lease_end' => ['leases', $r['lid'], '📄'],
            'rent' => ['leases', $r['lid'], '📄'], 'rent_words' => ['leases', $r['lid'], '📄'], 'advance' => ['leases', $r['lid'], '📄'], 'advance_words' => ['leases', $r['lid'], '📄'],
        ];
    } elseif ($kind === 'service') {
        $st = $pdo->prepare('SELECT * FROM partners WHERE id=?'); $st->execute([$ref]);
        $r = $st->fetch(PDO::FETCH_ASSOC);
        if (!$r) return null;
        $vars += [
            'partner_name' => esc($r['name']), 'partner_trade' => esc($r['trade']),
            'partner_rating' => (string)(float)$r['rating'], 'partner_jobs' => (string)(int)$r['jobs'],
            'partner_status' => esc($r['status']), 'partner_email' => esc($r['sub_email'] ?? ''),
        ];
    } elseif ($kind === 'receipt') {
        $p = null; $inv = null;
        $st = $pdo->prepare('SELECT * FROM payments WHERE id=?'); $st->execute([$ref]); $p = $st->fetch(PDO::FETCH_ASSOC);
        if (!$p) { $st = $pdo->prepare('SELECT * FROM invoices WHERE id=?'); $st->execute([$ref]); $inv = $st->fetch(PDO::FETCH_ASSOC); }
        if (!$inv && !$p) {
            $st = $pdo->prepare('SELECT * FROM receipts WHERE id=?'); $st->execute([$ref]); $rec = $st->fetch(PDO::FETCH_ASSOC);
            if ($rec) { $st = $pdo->prepare('SELECT * FROM invoices WHERE id=?'); $st->execute([$rec['inv']]); $inv = $st->fetch(PDO::FETCH_ASSOC); }
        }
        if (!$inv && $p) { $st = $pdo->prepare('SELECT * FROM invoices WHERE id=?'); $st->execute([$p['inv']]); $inv = $st->fetch(PDO::FETCH_ASSOC); }
        if (!$p && $inv) { $st = $pdo->prepare("SELECT * FROM payments WHERE inv=? AND status='Success' ORDER BY date DESC, id DESC LIMIT 1"); $st->execute([$inv['id']]); $p = $st->fetch(PDO::FETCH_ASSOC); }
        if (!$inv) return null;
        $amt = $p ? (int)$p['amount'] : (int)$inv['net'];
        $st = $pdo->prepare('SELECT l.u AS uid, l.t AS tid FROM leases l WHERE l.id=?'); $st->execute([$inv['l']]);
        $l = $st->fetch(PDO::FETCH_ASSOC);
        $un = $pr = $te = null;
        if ($l) {
            $st = $pdo->prepare('SELECT name, floor, p FROM units WHERE id=?'); $st->execute([$l['uid']]); $un = $st->fetch(PDO::FETCH_ASSOC);
            $st = $pdo->prepare('SELECT name, jur, holding FROM properties WHERE id=?'); $st->execute([$un['p']]); $pr = $st->fetch(PDO::FETCH_ASSOC);
            $st = $pdo->prepare('SELECT name, phone FROM tenants WHERE id=?'); $st->execute([$l['tid']]); $te = $st->fetch(PDO::FETCH_ASSOC);
        }
        $vars += [
            'receipt_id' => esc($p ? $p['id'] : ('RCP-' . $inv['id'])),
            'date' => esc($p ? $p['date'] : gmdate('d M Y')),
            'invoice_id' => esc($inv['id']), 'month' => esc($inv['m']), 'lease_id' => esc($inv['l']),
            'amount' => money_bd($amt), 'amount_words_en' => num_to_words_en($amt), 'amount_words_bn' => num_to_words_bn($amt) . ' টাকা মাত্র',
            'method' => esc($p ? $p['method'] : '—'), 'ref' => esc($p ? $p['ref'] : '—'),
            'tenant_name' => esc($te['name'] ?? '—'), 'tenant_phone' => esc($te['phone'] ?? '—'),
            'property_name' => esc($pr['name'] ?? '—'), 'property_address' => esc($pr ? trim(trim($pr['holding'] . ', ' . $pr['jur']), ' ,') : '—'),
            'unit_name' => esc($un['name'] ?? '—'), 'unit_id' => esc($l['uid'] ?? '—'), 'floor' => esc($un['floor'] ?? '—'),
        ];
        $links = [
            'tenant_name' => ['tenants', $l['tid'] ?? '', '👤'], 'tenant_phone' => ['tenants', $l['tid'] ?? '', '👤'],
            'property_name' => ['properties', $un['p'] ?? '', '🏢'], 'property_address' => ['properties', $un['p'] ?? '', '🏢'],
            'unit_name' => ['units', $l['uid'] ?? '', '🚪'], 'unit_id' => ['units', $l['uid'] ?? '', '🚪'],
            'invoice_id' => ['invoices', $inv['id'], '🧾'], 'month' => ['invoices', $inv['id'], '🧾'],
            'lease_id' => ['leases', $inv['l'], '📄'],
            'receipt_id' => ['payments', $p['id'] ?? '', '💳'], 'amount' => ['payments', $p['id'] ?? '', '💳'], 'method' => ['payments', $p['id'] ?? '', '💳'], 'ref' => ['payments', $p['id'] ?? '', '💳'],
        ];
    } else {
        return null;
    }
    return ['vars' => $vars, 'links' => $links];
}
function tpl_print_page($tpl, $merged, $kind) {
    $sig = $kind === 'receipt'
        ? '<div class="sig"><div>Authorized signature</div></div>'
        : '<div class="sig"><div>Party 1 signature</div><div>Party 2 signature</div><div>Witness 1</div><div>Witness 2</div></div>';
    return '<!doctype html><html lang="en"><head><meta charset="utf-8"><title>' . esc($tpl['title']) . '</title><style>'
        . '*{box-sizing:border-box}body{font-family:Inter,"Hind Siliguri",Arial,sans-serif;color:#101828;margin:0;padding:32px;background:#F4F6FA}'
        . '.page{max-width:800px;margin:0 auto;background:#fff;border:1px solid #E4EAF3;border-radius:16px;padding:44px}'
        . '.brand{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #2F80ED;padding-bottom:14px;margin-bottom:18px}'
        . '.brand img{display:block;margin-bottom:3px}.brand b{font-size:19px;color:#2F80ED;letter-spacing:-.3px}.brand small{display:block;font-size:9.5px;letter-spacing:1.6px;color:#8A94A6;text-transform:uppercase}'
        . '.ttl{font-size:15px;font-weight:700;color:#1A2433}'
        . '.tpl-body{font-family:Inter,"Hind Siliguri",Arial,sans-serif;font-size:13.5px;line-height:1.9;color:#1A2433;white-space:pre-wrap}'
        . '.sig{margin-top:38px;display:grid;grid-template-columns:1fr 1fr;gap:26px}.sig div{border-top:1px dashed #98A2B3;padding-top:8px;font-size:12px;color:#475467}'
        . '.noprint{position:fixed;top:16px;right:16px}.btn{font:600 13px Inter;padding:9px 16px;border-radius:10px;border:1px solid #D0D5DD;background:#fff;cursor:pointer}.btn.p{background:#2F80ED;color:#fff;border-color:#2F80ED}'
        . '@media print{body{background:#fff;padding:0}.page{border:0;box-shadow:none}.noprint{display:none}}'
        . '</style></head><body><div class="noprint"><button class="btn" onclick="window.print()">🖨 Print / Save PDF</button></div><div class="page">'
        . '<div class="brand"><div>' . print_brand_img() . '<small>KEY RESPONSIBILITY TAKER</small></div><div class="ttl">' . esc($tpl['title']) . '</div></div>'
        . '<div class="tpl-body">' . $merged . '</div>'
        . $sig
        . '<div style="margin-top:26px;padding-top:12px;border-top:1px dashed #E4EAF3;font-size:11px;color:#8A94A6;text-align:center">System-generated by KRTaker — your AI caretaker · Verify at krtaker.com</div>'
        . '</div></body></html>';
}
function email_sample_vars($id) {
    switch ($id) {
        case 'otp': return ['code' => '483920', 'name' => 'Tahmina Akter', 'expiry' => '5 minutes'];
        case 'welcome': return ['name' => 'Tahmina Akter', 'trial_end' => '26 Jun 2026', 'workspace_url' => 'https://krtaker.com/app-v3/'];
        case 'collections': return ['unpaid' => '3', 'total' => '৳4,82,000', 'items' => '<tr><td style="padding:8px 10px;border-bottom:1px solid #E4EAF3;font-size:13px"><b>INV-2026-0011</b><br><span style="color:#8A94A6;font-size:11px">Sultana Rahman · Green View Residency</span></td><td style="padding:8px 10px;border-bottom:1px solid #E4EAF3;font-size:13px">2026-06</td><td style="padding:8px 10px;border-bottom:1px solid #E4EAF3;font-size:13px;text-align:right">৳32,000</td></tr><tr><td style="padding:8px 10px;font-size:13px"><b>INV-2026-0012</b><br><span style="color:#8A94A6;font-size:11px">Rahim Steel · Banani Commercial Tower</span></td><td style="padding:8px 10px;font-size:13px">2026-06</td><td style="padding:8px 10px;font-size:13px;text-align:right">৳4,50,000</td></tr>'];
        case 'rent_reminder': return ['tenant_name' => 'Sultana Rahman', 'invoice_id' => 'INV-2026-0011', 'month' => '2026-06', 'amount' => '32,000', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)'];
        case 'invoice': return ['tenant_name' => 'Sultana Rahman', 'invoice_id' => 'INV-2026-0011', 'month' => '2026-06', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)', 'amount' => '32,000', 'due' => '32,000', 'due_color' => '#B91C1C'];
        case 'receipt': return ['tenant_name' => 'Sultana Rahman', 'receipt_id' => 'PAY-010', 'date' => '02 Aug 2026', 'amount' => '25,000', 'amount_words_en' => 'Twenty-Five Thousand', 'amount_words_bn' => 'পঁচিশ হাজার টাকা মাত্র', 'method' => 'bKash', 'ref' => '8T5XK2QZ', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)', 'month' => '2026-06'];
        case 'renewal_status': return ['tenant_name' => 'Sultana Rahman', 'property' => 'Dhanmondi Apartment', 'unit' => 'Apartment 7B (U-010)', 'lease' => 'L-007', 'status' => 'Approved', 'new_end' => '14 Dec 2027', 'new_rent' => '42,000', 'note' => 'Thank you for being a valued tenant.'];
        case 'welcome_bn': return ['name' => 'তহমিনা আক্তার', 'trial_end' => '২৬ জুন ২০২৬', 'workspace_url' => 'https://krtaker.com/app-v3/'];
        case 'rent_reminder_bn': return ['tenant_name' => 'সুলতানা রহমান', 'invoice_id' => 'INV-2026-0011', 'month' => '2026-06', 'amount' => '32,000', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)'];
        case 'invoice_bn': return ['tenant_name' => 'সুলতানা রহমান', 'invoice_id' => 'INV-2026-0011', 'month' => '2026-06', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)', 'amount' => '32,000', 'due' => '32,000', 'due_color' => '#B91C1C'];
        case 'receipt_bn': return ['tenant_name' => 'সুলতানা রহমান', 'receipt_id' => 'PAY-010', 'date' => '০২ আগস্ট ২০২৬', 'amount' => '25,000', 'amount_words_en' => 'Twenty-Five Thousand', 'amount_words_bn' => 'পঁচিশ হাজার টাকা মাত্র', 'method' => 'bKash', 'ref' => '8T5XK2QZ', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)', 'month' => '2026-06'];
        case 'move_out_bn': return ['name' => 'সুলতানা রহমান', 'property' => 'Green View Residency', 'unit_name' => 'Flat 3B (U-001)', 'move_out_date' => '০১ আগস্ট ২০২৬', 'lease' => 'L-005', 'rent_due' => '0', 'util_due' => '2,400', 'dmg_due' => '0', 'deposit' => '90,000', 'balance' => '87,600', 'status' => 'Refundable', 'status_color' => '#1E8449', 'workspace_url' => 'https://krtaker.com/app-v3/'];
        case 'arrears': return ['tenant_name' => 'Sultana Rahman', 'invoice_id' => 'INV-2026-0011', 'month' => '2026-06', 'amount' => '32,000', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)', 'total_due' => '96,000', 'days_overdue' => '21', 'pay_url' => 'https://krtaker.com/app-v3/'];
        case 'owner_statement': return ['owner_name' => 'Alamgir Kabir', 'property' => 'Green View Residency', 'month_label' => 'July 2026', 'gross' => '140,000', 'collected' => '130,000', 'tds' => '3,000', 'service' => '7,000', 'expenses' => '5,500', 'net' => '114,500', 'collect_rate' => '93', 'paid_invoices' => '4', 'total_invoices' => '5', 'payout_line' => 'Payout: ৳114,500 · Paid', 'dashboard_url' => 'https://krtaker.com/app-v3/#/statements'];
        case 'notice_email': return ['org_name' => 'KRTaker', 'tenant_name' => 'Sultana Rahman', 'notice_title' => 'Utility schedule for August', 'notice_body' => 'Electricity readings will be taken on 28 August, 10am–2pm. Please ensure access to your meter.', 'author' => 'Arif Chowdhury', 'posted_date' => '12 Aug 2026', 'portal_url' => 'https://krtaker.com/app-v3/'];
        case 'arrears_bn': return ['tenant_name' => 'সুলতানা রহমান', 'invoice_id' => 'INV-2026-0011', 'month' => '2026-06', 'amount' => '32,000', 'property' => 'Green View Residency', 'unit' => 'Flat 3B (U-001)', 'total_due' => '96,000', 'days_overdue' => '২১', 'pay_url' => 'https://krtaker.com/app-v3/'];
    }
    return [];
}

