<script setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import GuideScreen from '../components/GuideScreen.vue'
import { lang, t as tr } from '../lib/i18n'

const router = useRouter()
const q = ref('')
const open = ref({})   // section id -> set of open item ids (or 'all')

// ── Wiki content (V2.24: subscriber wiki — accurate to the live system) ──
// Alert types, per-user prefs, admin master switches and email classes are
// all documented from the actual implementation (SETTINGS_DEFAULTS,
// ADMIN_SETTING_DEFAULTS, notify_ok flags, app-kr-alert targets, mail_switch).
const SECTIONS = [
  {
    id: 'guides', ico: '🖼️', title: tr('Visual guides (step-by-step)'),
    items: [
      {
        t: tr('Logging in & setting up 2FA'),
        tag: tr('🖼️ visual'),
        b: tr('Your login is password + one-time code. Once you enable 2FA, every sign-in asks for a code from your email inbox or an authenticator app — so even a leaked password alone cannot get in.'),
        g: {
          variant: 'login',
          url: 'app.krtaker.com',
          highlights: [
            { x: 37, y: 30, w: 26, h: 8.5, t: tr('Enter your email'), d: tr('The account email you were invited with (e.g. owner@krtaker.com).') },
            { x: 37, y: 41.5, w: 26, h: 8.5, t: tr('Enter your password'), d: tr('At least 8 characters. After several failed attempts the account locks briefly.') },
            { x: 37, y: 53, w: 26, h: 8.5, t: tr('Enter the 6-digit code'), d: tr('Only appears when 2FA is on: emailed to you or generated by your authenticator app.') },
            { x: 37, y: 64.5, w: 26, h: 11, t: tr('Sign in'), d: tr('Tip: enable 2FA in Settings → Security so every login needs a fresh code.') },
          ],
        },
      },
      {
        t: tr('Your first look: the Overview dashboard'),
        tag: tr('🖼️ visual'),
        b: tr('The Overview hub is your control room. Sidebar hubs on the left, live KPIs on top, the AI Caretaker and your latest alerts below.'),
        g: {
          variant: 'dash',
          url: 'app.krtaker.com/app-v3/#/overview',
          highlights: [
            { x: 84, y: 3, w: 10, h: 8, t: tr('Notification bell'), d: tr('Unread count badge. Opens the Notifications screen with filter pills.') },
            { x: 72, y: 17, w: 20, h: 13, t: tr('Alerts KPI'), d: tr('Count of open alerts. Click to jump to the Notifications screen.') },
            { x: 18, y: 37, w: 38, h: 24, t: tr('AI Caretaker (KR)'), d: tr('Ask questions in plain language: "who is behind on rent?" — it answers from live data.') },
            { x: 0.5, y: 15, w: 15.5, h: 7.5, t: tr('Sidebar hubs'), d: tr('Overview, Portfolio, Finance, BMS, Community, Legal, Safety, Admin — your role decides what shows.') },
          ],
        },
      },
      {
        t: tr('Reading your notifications'),
        tag: tr('🖼️ visual'),
        b: tr('All alerts land in one inbox. Filter by type, open the record, or clear the queue.'),
        g: {
          variant: 'notify',
          url: 'app.krtaker.com/app-v3/#/notifications',
          highlights: [
            { x: 72, y: 2, w: 25, h: 8, t: tr('Mark all read'), d: tr('One tap clears the unread badge. "Clear all" dismisses the whole list.') },
            { x: 4, y: 16, w: 55, h: 10, t: tr('Filter pills'), d: tr('All / SLA / Compliance / Arrears / Renewals — one-tap filtering by alert type.') },
            { x: 4, y: 28, w: 62, h: 15, t: tr('Severity chips'), d: tr('Red = critical, orange = warning, blue = info. Critical items need action first.') },
            { x: 4, y: 64, w: 62, h: 15, t: tr('Open the record'), d: tr('Click any alert to jump straight to the invoice, lease or job that needs attention.') },
          ],
        },
      },
      {
        t: tr('Creating an invoice & tracking payment'),
        tag: tr('🖼️ visual'),
        b: tr('Invoices are the heart of Finance. Generate them per lease, email them, and watch the status move Draft → Sent → Paid as money comes in.'),
        g: {
          variant: 'finance',
          url: 'app.krtaker.com/app-v3/#/finance/invoices',
          highlights: [
            { x: 78, y: 2, w: 19, h: 8, t: '➕ New invoice', d: tr('Pick the lease, period and amount — or auto-generate for the whole month.') },
            { x: 84, y: 42, w: 10, h: 8, t: tr('Paid status'), d: tr('When a receipt is recorded, the invoice flips to Paid and Collections updates.') },
            { x: 84, y: 56, w: 10, h: 8, t: tr('Draft status'), d: tr('Drafts are not yet sent. Open it to review, then send / email the tenant.') },
          ],
        },
      },
      {
        t: tr('Posting a notice & emailing tenants'),
        tag: tr('🖼️ visual'),
        b: tr('Post announcements to the notice board and optionally email every emailable tenant in one click.'),
        g: {
          variant: 'notice',
          url: 'app.krtaker.com/app-v3/#/community/notices',
          highlights: [
            { x: 78, y: 2, w: 19, h: 8, t: '➕ New notice', d: tr('Opens the notice composer: title + details.') },
            { x: 5, y: 63, w: 55, h: 11, t: tr('Also email to tenants'), d: tr('Toggle to broadcast. Shows the live recipient count — it respects opt-outs and the docs master switch.') },
            { x: 72, y: 63, w: 24, h: 11, t: tr('Post notice'), d: tr('Publishes to the board. Emails are queued (10/10-min per IP rate limit applies).') },
          ],
        },
      },
      {
        t: tr('Opening & working a support ticket'),
        tag: tr('🖼️ visual'),
        b: tr('The support desk tracks every request from Open to Closed with a shared conversation thread.'),
        g: {
          variant: 'support',
          url: 'app.krtaker.com/app-v3/#/community/support',
          highlights: [
            { x: 80, y: 1.5, w: 18, h: 7.5, t: '➕ New ticket', d: tr('Subject, category (General/Billing/Technical/…), priority and details.') },
            { x: 4, y: 13, w: 22, h: 10, t: tr('Open KPI'), d: tr('Live counters: Open / In progress / Resolved across all tickets.') },
            { x: 3, y: 32, w: 38, h: 16, t: tr('Ticket row'), d: tr('Category pill, ticket ID (SUP-XXX), priority + status chips. Click to open the drawer.') },
            { x: 50, y: 77, w: 46, h: 8.5, t: tr('Reply box'), d: tr('Type and press Send or Enter — the reply lands in the shared thread.') },
            { x: 50, y: 88, w: 46, h: 7, t: tr('Status buttons'), d: tr('Open → In Progress → Resolved → Closed with one click; priority can be changed any time.') },
          ],
        },
      },
      {
        t: tr('Tuning notification & security settings'),
        tag: tr('🖼️ visual'),
        b: tr('Settings controls what YOU receive and how secure your account is. Every toggle here only affects your own inbox.'),
        g: {
          variant: 'settings',
          url: 'app.krtaker.com/app-v3/#/settings',
          highlights: [
            { x: 88, y: 5, w: 9, h: 12, t: tr('Per-user toggles'), d: tr('Rent reminders, collections digest, web push and more — all default ON.') },
            { x: 3, y: 63, w: 55, h: 13, t: tr('Two-factor auth (2FA)'), d: tr('Enable email OTP or authenticator TOTP. After this, login needs your password + a fresh code.') },
            { x: 3, y: 78, w: 55, h: 13, t: tr('Change password'), d: tr('New passwords must be at least 8 characters (enforced server-side).') },
          ],
        },
      },
      {
        t: tr('The tenant portal at a glance'),
        tag: tr('🖼️ visual'),
        b: tr('Tenants log into their own portal (app-portal) where they see their lease, invoices and notices — and can pay online.'),
        g: {
          variant: 'tenant',
          url: 'app-portal.krtaker.com',
          highlights: [
            { x: 3, y: 8, w: 94, h: 20, t: tr('My lease'), d: tr('Unit, monthly rent and the next due date — always visible at the top.') },
            { x: 82, y: 40, w: 15, h: 12, t: tr('Pay'), d: tr('Online payment via the configured gateway (SSLCommerz); the receipt reconciles in Finance automatically.') },
            { x: 3, y: 66, w: 94, h: 20, t: tr('Notice board'), d: tr('Tenants see your public announcements — no email address needed.') },
          ],
        },
      },
    ],
  },
  {
    id: 'start', ico: '🚀', title: tr('Getting started'),
    items: [
      {
        t: tr('What is KRTaker?'),
        b: tr('KRTaker (Key Responsibility Taker) is a property & facility management platform for owners, managers and staff. It covers the full rental lifecycle — units, tenants, leases, invoices, receipts, payments, maintenance, compliance, legal, safety and analytics — all in one dashboard.\n\nEvery screen is organized into hubs: Overview, Portfolio, Finance, BMS, Community, Legal, Operations, Safety & Security and Admin. The sidebar shows only the modules your role can use.'),
      },
      {
        t: tr('Who can use the app?'),
        b: tr('Accounts are role-based: Owner, Manager, Accountant, Service Manager, Operations, and staff sub-accounts. Owners see everything; staff see only their modules. A senior user can "Switch role" from the sidebar bottom card to temporarily view the app as a subordinate user (read-only for higher-rank data).'),
      },
      {
        t: tr('How do I get help or support?'),
        b: tr('Open the Support module (Community hub) for the built-in support desk — raise a ticket and the team replies within the SLA for its priority. For urgent issues, contact support@krtaker.com or WhatsApp +880 1844-680068. The public 📖 Help center (krtaker.com/docs.html) has step-by-step guides for every role, and the AI Caretaker (KR) in the Overview hub answers operational questions 24/7.'),
      },
      {
        t: tr('What are the support SLAs?'),
        b: tr('Support tickets carry a service-level target based on priority:\n\n• 🚨 Urgent — first response within 4 hours, resolution within 24 hours\n• 🔴 High — response within 24 hours, resolution within 72 hours\n• 🟠 Medium — response within 72 hours, resolution within 7 days\n• 🟢 Low — response within 5 days, resolution within 10 days\n\nEvery ticket shows a live SLA chip (🟢 on track / 🟠 at risk / 🔴 breached) in the Support list and drawer. Breached tickets are escalated to the operations lead automatically.'),
      },
      {
        t: tr('How do refunds and cancellations work?'),
        b: tr('Subscriptions are billed monthly or annually via bKash, Nagad, SSLCommerz or bank transfer. You can cancel any time from Settings → Subscription (or by emailing support@krtaker.com) — access continues until the end of the paid period, no lock-in. Refunds: within the first 14 days of a paid plan, if you have not used the paid features, we refund the full amount within 7 business days. After 14 days, fees are non-refundable except where required by law (see the Terms, section 3). Annual plans are prorated only in the 14-day window.'),
      },
    ],
  },
  {
    id: 'alerts', ico: '🔔', title: tr('Alerts & notifications'),
    items: [
      {
        t: tr('What alert types exist?'),
        b: tr('The system watches your portfolio and raises alerts in these categories:\n\n• 🔧 SLA — maintenance/service-level jobs that breached their promise time\n• 📋 Compliance — certificates, licenses or inspections expired (or expiring soon)\n• 💰 Arrears — tenants behind on rent\n• 📅 Renewals — leases that are about to end or need renewal\n• 🔔 System — security and account events\n\nEach alert has a severity (info / warning / critical) and links straight to the record that needs attention.'),
      },
      {
        t: tr('Alert severities & colors'),
        b: tr('Every alert carries a severity that tells you how fast to act:\n\n• 🔴 Critical — immediate attention (SLA breach, security event)\n• 🟠 Warning — act this week (compliance expiring soon, missed rent)\n• 🔵 Info — awareness (lease renewals, system notices)\n\nThe colored chip on each notification matches the severity, and the Notifications screen lets you filter by type so critical items never get buried.'),
      },
      {
        t: tr('Who receives alerts?'),
        b: tr('Since V2.23, alerts fan out to both the account owner and all active staff (Manager, Service Manager, Operations). Previously staff saw nothing — now every active team member receives SLA, compliance, arrears and renewal alerts so nothing slips through. Parcel-owner-specific alerts (land parcels, NRB vacancies) stay targeted to the parcel owner only.'),
      },
      {
        t: tr('Where do I see alerts?'),
        b: tr('Open the 🔔 Notifications screen (from the bell in the header, or directly). You get: a count of unread items, filter pills by type, one-tap "Mark all read", and "Clear all" to dismiss. Clicking an alert opens the exact record (invoice, lease, maintenance job…) in its module.'),
      },
      {
        t: tr('How do I turn alert categories on/off?'),
        b: tr('Settings → Notifications: each category (SLA, Compliance, Arrears, Renewals) has its own toggle. Turn off the ones you do not want in your inbox — your staff members control their own toggles independently.'),
      },
    ],
  },
  {
    id: 'prefs', ico: '🎛️', title: tr('Notification preferences'),
    items: [
      {
        t: tr('Per-user email toggles'),
        b: tr('Your own Settings screen controls which emails you personally receive (all default ON):\n\n• Rent reminders (notify_rent)\n• Collections / payment digests (notify_collections)\n• Lease renewals (notify_renewal)\n• Document emails — invoices, receipts (notify_docs)\n• WhatsApp reminders (wa_reminders, if your phone is set)\n• Weekly email digest (email_digest)\n• Product/premium announcements (notify_premium)\n\nThese are per-account: switching them off only silences YOUR inbox, never other users.'),
      },
      {
        t: tr('Browser (web push) notifications'),
        b: tr('Settings → Browser notifications lets you subscribe your device to push alerts. Enable the browser permission when prompted, and the app registers a VAPID push subscription. You can see how many devices are subscribed and unsubscribe any time. Pushes arrive even when the app tab is closed, but only while the browser itself is running.'),
      },
      {
        t: tr('Master switches (admin controlled)'),
        b: tr('The account admin can disable an entire mail class for the whole workspace (Settings → App → Email & notifications): welcome mail, rent reminders, collections, documents, renewals, and the digest. Per-user toggles still apply on top — an email is only sent when BOTH the master switch AND the user toggle allow it.'),
      },
      {
        t: tr('Opt-out for tenants'),
        b: tr('Tenants and partners can opt out of document emails (notify_docs). The system respects those opt-outs everywhere: invoice emails, receipts, lease documents, and notice broadcasts.'),
      },
    ],
  },
  {
    id: 'email', ico: '📧', title: tr('Email you receive'),
    items: [
      {
        t: tr('Welcome & onboarding'),
        b: tr('New accounts get a welcome email with login details. Owners can also invite staff sub-accounts, who get their own credentials.'),
      },
      {
        t: tr('Rent reminders'),
        b: tr('Automatic reminders go out before/at rent due dates to tenants (and owners) based on the rent-reminder schedule. A daily cron (00:30 UTC) scans active leases and sends only to users who have not opted out.'),
      },
      {
        t: tr('Collections digest'),
        b: tr('Owners receive a periodic collections digest summarizing money collected across properties — gross, collected, outstanding — plus the automated owner statement emails (monthly statement run from the Statements screen).'),
      },
      {
        t: tr('Notices broadcast (email)'),
        b: tr('When you post a notice on the board, you can optionally "Also email to tenants". The recipient count is shown live — it respects tenant opt-outs and the document master switch. Each notice records how many emails were sent (📨 badge + emailed count).'),
      },
      {
        t: tr('Rate limits & delivery'),
        b: tr('To protect deliverability, email sends are throttled per IP: 10 sends per 10 minutes for invoice emails, notice broadcasts, receipt emails and tenant reminders. If you hit the limit, wait a few minutes and retry. All outbound mail goes through the configured SMTP queue.'),
      },
    ],
  },
  {
    id: 'security', ico: '🛡️', title: tr('Security & privacy'),
    items: [
      {
        t: tr('Two-factor authentication (2FA)'),
        b: tr('Enable 2FA in Settings → Security. Two methods are supported: email OTP codes (a one-time code sent to your inbox at login) and authenticator TOTP apps. Once enabled, login requires your password plus the code — protecting you even if the password leaks.'),
      },
      {
        t: tr('Session & password policy'),
        b: tr('Sessions expire automatically after the configured TTL (Settings → App → Security; default 7 days, owners can pick 12h–30d, the super-admin session is locked to 12h). New passwords must be at least 8 characters (enforced server-side). After several failed logins the account locks briefly to stop brute-force.'),
      },
      {
        t: tr('Your data & GDPR export'),
        b: tr('You own your data. From a tenant record → 📦 Data export, you can download a full JSON export of that tenant (leases, invoices, payments). The audit log (super-admin panel) records who did what, and backups are kept on a rotation.'),
      },
      {
        t: tr('Alerts about security events'),
        b: tr('New logins from unfamiliar devices and other security events raise a system alert in your Notifications so you can react immediately.'),
      },
    ],
  },
  {
    id: 'modules', ico: '🧭', title: tr('Module guides'),
    items: [
      {
        t: tr('Finance hub (💰)'),
        tag: tr('🖼️ visual'),
        b: tr('The Finance hub is your money command center — invoices, receipts, collections, statements and accounts all reconcile into one set of KPIs.'),
        g: {
          variant: 'finhub',
          url: 'app.krtaker.com/app-v3/#/finance',
          highlights: [
            { x: 16.5, y: 3.5, w: 81, h: 10, t: tr('Money KPIs'), d: tr('Gross billed, collected and outstanding — recomputed automatically from invoices and receipts, no manual math.') },
            { x: 1, y: 4, w: 15.5, h: 7.5, t: tr('Invoices'), d: tr('Generate monthly rent invoices per lease; statuses move Draft → Sent → Paid.') },
            { x: 1, y: 12.5, w: 15.5, h: 7.5, t: tr('Receipts'), d: tr('Record a rent payment and a receipt (RCPT-XXXX) is issued instantly.') },
            { x: 1, y: 21, w: 15.5, h: 7.5, t: tr('Collections'), d: tr('See exactly who owes what, with overdue rows highlighted.') },
            { x: 1, y: 55, w: 15.5, h: 7.5, t: tr('Statements'), d: tr('Monthly owner statements; the 📧 Statement Emails tab auto-sends them on the day you configure (V2.21).') },
            { x: 72, y: 41, w: 25, h: 8, t: tr('Invoice statuses'), d: tr('Draft = not sent yet, Sent = emailed, Paid = receipt recorded. Click any invoice to email or record payment.') },
          ],
        },
      },
      {
        t: tr('BMS hub (🔧)'),
        tag: tr('🖼️ visual'),
        b: tr('Building & Maintenance Services covers the physical estate — maintenance tickets with SLA tracking, vendors, staff, meters and gate visits.'),
        g: {
          variant: 'bms',
          url: 'app.krtaker.com/app-v3/#/bms',
          highlights: [
            { x: 1, y: 4, w: 16, h: 8, t: tr('Maintenance'), d: tr('Raise work tickets per unit with category and priority. Staff track them against an SLA clock.') },
            { x: 1, y: 13, w: 16, h: 8, t: tr('Vendors'), d: tr('Contractor marketplace: request offers, accept/reject, issue work orders and run vendor payouts.') },
            { x: 1, y: 30, w: 16, h: 8, t: tr('Meter readings'), d: tr('Record utility readings and generate utility invoices from them.') },
            { x: 76, y: 3.5, w: 21, h: 8, t: '➕ Raise ticket', d: tr('Unit, category, priority, title + description. Tenants can also report issues themselves.') },
            { x: 60, y: 30, w: 37, h: 8.5, t: tr('SLA clock'), d: tr('Every ticket shows time left. Breached SLA jobs turn red and raise a 🔔 alert to the team.') },
            { x: 60, y: 39.5, w: 37, h: 8.5, t: tr('SLA on track'), d: tr('Green/blue chips mean the job is still within its promise time.') },
            { x: 45, y: 30, w: 13, h: 27, t: tr('Liability flags'), d: tr('Landlord / Tenant / Shared — who pays for this fix is decided up front and stays visible.') },
          ],
        },
      },
      {
        t: tr('Community hub (📢)'),
        tag: tr('🖼️ visual'),
        b: tr('Community is tenant & partner engagement — the notice board, referral rewards, identity trust records and the support desk.'),
        g: {
          variant: 'community',
          url: 'app.krtaker.com/app-v3/#/community',
          highlights: [
            { x: 1, y: 4, w: 17, h: 8, t: tr('Notices'), d: tr('Post announcements to the notice board for tenants and owners.') },
            { x: 1, y: 13, w: 17, h: 8, t: tr('Referrals'), d: tr('Invite friends with your referral code and earn ৳5,000 per active subscriber.') },
            { x: 1, y: 22, w: 17, h: 8, t: tr('Trust (NID)'), d: tr('Identity & document trust records — verified, pending or rejected.') },
            { x: 1, y: 31, w: 17, h: 8, t: tr('Support'), d: tr('The built-in help desk — open tickets, reply in threads, track status.') },
            { x: 76, y: 3.5, w: 21, h: 8, t: '➕ New notice', d: tr('Title + details. Optionally broadcast by email in the same step.') },
            { x: 20, y: 44, w: 58, h: 11, t: tr('Also email to tenants'), d: tr('Shows the live recipient count — respects opt-outs and the docs master switch.') },
            { x: 18, y: 63, w: 66, h: 10, t: tr('Referral code'), d: tr('Share KR-XXXX with friends — you earn ৳5,000 when they activate.') },
          ],
        },
      },
      {
        t: tr('Legal hub (⚖️)'),
        tag: tr('🖼️ visual'),
        b: tr('Legal covers risk & compliance — certificates and licenses with expiry tracking, disputes, and resident services.'),
        g: {
          variant: 'legal',
          url: 'app.krtaker.com/app-v3/#/legal',
          highlights: [
            { x: 1, y: 4, w: 16, h: 8, t: tr('Compliance'), d: tr('Certificates, licenses and inspections with expiry dates. The scanner raises alerts before anything lapses.') },
            { x: 1, y: 13, w: 16, h: 8, t: tr('Cases'), d: tr('Track disputes with a status flow: Open → In Progress → Resolved, linked to leases.') },
            { x: 17, y: 3.5, w: 28, h: 10, t: tr('Compliance KPI'), d: tr('Total items plus how many expire within 30 days — a live risk count.') },
            { x: 17, y: 38, w: 34, h: 10, t: tr('Expiring soon'), d: tr('Items inside the window are flagged red so renewals never sneak up on you.') },
            { x: 17, y: 27, w: 34, h: 10, t: tr('Valid items'), d: tr('Green status = nothing to do. Upload renewals from the record to keep it green.') },
            { x: 17, y: 66, w: 60, h: 9, t: tr('Open case'), d: tr('Each case shows its status chip; clicking it opens the full record with timeline.') },
          ],
        },
      },
      {
        t: tr('Safety & Security hub (🏠)'),
        tag: tr('🖼️ visual'),
        b: tr('Safety & Security groups the physical & digital safety tooling — connected systems, fire safety, land, build, KYC and inspections.'),
        g: {
          variant: 'safety',
          url: 'app.krtaker.com/app-v3/#/safety',
          highlights: [
            { x: 1, y: 4, w: 16, h: 8, t: tr('Building systems'), d: tr('Connected devices & building systems with live online/offline status.') },
            { x: 1, y: 36, w: 16, h: 8, t: tr('Fire safety'), d: tr('Fire certificates, drill logs and equipment checks — expiry tracked like compliance.') },
            { x: 1, y: 44.5, w: 16, h: 8, t: tr('KYC'), d: tr('Know-Your-Customer records for partners and tenants.') },
            { x: 1, y: 53, w: 16, h: 8, t: tr('Inspections'), d: tr('Scheduled property inspections with checklists and due dates.') },
            { x: 75, y: 3.5, w: 22, h: 8, t: '➕ Add device', d: tr('Register a new connected device against a property/unit.') },
            { x: 18, y: 56, w: 66, h: 10, t: tr('Fire certificate'), d: tr('Valid until date + status chip. Renewal is one upload away.') },
            { x: 18, y: 73, w: 66, h: 9, t: tr('Inspection due'), d: tr('Scheduled checks surface here with a count of what is due this week.') },
          ],
        },
      },
      {
        t: tr('Portfolio & properties (🏢)'),
        tag: tr('🖼️ visual'),
        b: tr('Portfolio is the master data layer — the Properties → Units → Tenants → Leases hierarchy plus onboarding, leads, documents and insurance.'),
        g: {
          variant: 'portfolio',
          url: 'app.krtaker.com/app-v3/#/portfolio',
          highlights: [
            { x: 1, y: 4, w: 15.5, h: 8, t: tr('Properties'), d: tr('Every building with occupancy and monthly revenue at a glance.') },
            { x: 1, y: 12.5, w: 15.5, h: 8, t: tr('Units'), d: tr('Drill into a property to manage its units — status, floor, size, rent.') },
            { x: 1, y: 21, w: 15.5, h: 8, t: tr('Tenants'), d: 'Each unit\'s tenant record with lease, documents and payment history.' },
            { x: 1, y: 29.5, w: 15.5, h: 8, t: tr('Leases'), d: tr('Active and expiring leases; renewals raise 🔔 alerts automatically.') },
            { x: 76, y: 3.5, w: 21, h: 8, t: '➕ New property', d: tr('Name, type, jurisdiction, address — the first step of onboarding a building.') },
            { x: 18, y: 14, w: 60, h: 12, t: tr('Property card'), d: tr('Click any property to see its units, then tenants, then leases — the whole hierarchy.') },
            { x: 25, y: 62, w: 55, h: 9, t: tr('Core hierarchy'), d: tr('Properties → Units → Tenants → Leases is the backbone every module builds on.') },
          ],
        },
      },
      {
        t: tr('Recording a receipt & reconciling (💳)'),
        tag: tr('🖼️ visual'),
        b: tr('When rent comes in, record it against the invoice — a receipt is issued and Collections updates itself. No double-entry needed.'),
        g: {
          variant: 'receipt',
          url: 'app.krtaker.com/app-v3/#/finance/receipts',
          highlights: [
            { x: 3, y: 4, w: 46, h: 86, t: tr('Open the invoice'), d: 'Pick the invoice the tenant is paying. You see the tenant, amount, due date and what method they\'ll use.' },
            { x: 6, y: 68, w: 34, h: 13, t: '💳 Record payment', d: tr('Enter amount, method (bKash, bank, cash) and date, then save.') },
            { x: 52, y: 4, w: 45, h: 86, t: tr('Receipt auto-issued'), d: tr('A receipt (RCPT-XXXX) is created instantly and emailed if the tenant allows document emails.') },
            { x: 55, y: 40, w: 38, h: 12, t: tr('Status flips to Paid'), d: tr('The invoice turns Paid, the outstanding KPI drops, and Collections reconciles.') },
          ],
        },
      },
      {
        t: tr('Raising a maintenance ticket (🔧)'),
        tag: tr('🖼️ visual'),
        b: tr('A ticket is how the team fixes things: raise it, the SLA clock starts, staff work it to Done. Tenants can raise tickets from their portal too.'),
        g: {
          variant: 'maint',
          url: 'app.krtaker.com/app-v3/#/bms/maintenance',
          highlights: [
            { x: 3, y: 4, w: 46, h: 86, t: tr('Raise the ticket'), d: tr('Unit, category (plumbing, electrical, HVAC…), priority and a short title + description.') },
            { x: 3, y: 33, w: 40, h: 10, t: tr('Priority decides SLA'), d: tr('High priority = shorter promise time. The clock starts the moment the ticket is created.') },
            { x: 52, y: 4, w: 45, h: 86, t: tr('Ticket is live'), d: tr('The team sees it instantly with an MT-XXX id. Staff can claim it and post updates.') },
            { x: 55, y: 32, w: 38, h: 12, t: tr('SLA countdown + liability'), d: tr('Time left is always visible; the Landlord/Tenant/Shared flag decides who pays.') },
            { x: 55, y: 58, w: 38, h: 12, t: 'Timeline', d: tr('Created → Assigned → Done with timestamps. SLA breaches raise a 🔔 alert automatically.') },
          ],
        },
      },
    ],
  },
  {
    id: 'support', ico: '🎧', title: tr('Support & ticketing'),
    items: [
      {
        t: tr('How do I open a ticket?'),
        b: tr('Support → ➕ New ticket. Give it a subject, choose a category (General, Billing, Technical, Feature request, Account, Other) and a priority (Low → Urgent), then describe the issue. Tickets get an ID like SUP-014 and appear instantly in the list. The workspace owner is notified by push when a ticket is opened.'),
      },
      {
        t: tr('The ticket workflow'),
        b: tr('Every ticket moves through a status flow:\n\n• Open — just created, waiting for attention\n• In Progress — someone is working it\n• Resolved — the fix/answer has been delivered\n• Closed — done, no more replies expected\n\nFrom the ticket drawer you can advance status with one click and change priority any time (High/Urgent tickets are highlighted in red).'),
      },
      {
        t: tr('Replies & conversation'),
        b: tr('Tickets are threaded: open any ticket to see the full conversation (opened message + every reply with author and timestamp). Type in the reply box and press Send (or Enter). Replies update the ticket timestamp so the team can see it is active again. The thread is shared — everyone with the support module sees the same history.'),
      },
      {
        t: tr('Search, filter & export'),
        b: tr('The support screen has a live search box (matches subject, sender, category — anything), status / priority / category filters, and Grid/List views. ⬇ CSV exports the current filtered set for offline records. Category pills across the top give one-tap filtering by type.'),
      },
      {
        t: tr('Ticket KPIs & category filters'),
        b: tr('The top of the Support screen shows three live counters — Open, In progress and Resolved — so the team can see the workload at a glance. Category pills (General, Billing, Technical, Feature request, Account, Other) filter the list in one tap, and High/Urgent tickets are highlighted in red so nothing urgent slips. Search matches subject, sender, category and ticket ID, and every ticket keeps a full conversation thread that all staff with support access can see.'),
      },
      {
        t: tr('Escalation & help'),
        b: tr('Stuck on a product question first? Check the 📚 Wiki — most answers live there. If a ticket needs urgent eyes, set priority to Urgent; the High-prio KPI on the dashboard flags it. For billing emergencies use the Billing category so the finance team can pick it up quickly.'),
      },
    ],
  },
  {
    id: 'advanced', ico: '🧠', title: tr('Advanced features'),
    items: [
      {
        t: tr('AI Caretaker (KR) 🤖'),
        b: tr('The AI Caretaker in Overview answers operational questions about your portfolio in natural language — ask "who is behind on rent?" or "show expiring compliance" and it pulls from live data. It also powers smart suggestions and the kr_alert_scan that raises SLA/compliance/arrears/renewal alerts automatically.'),
      },
      {
        t: tr('Automation: rent reminders, statements, notices'),
        b: tr('KRTaker automates the collection loop end-to-end:\n\n• Rent reminders — a daily cron (00:30 UTC) emails tenants before/at due dates (respects per-user toggles + admin master switch)\n• Owner statements — computed monthly per property; the Statement Emails tab emails them on the day you configure (V2.21)\n• Notice broadcast — one click emails a notice board post to every emailable tenant (V2.22)\n\nEvery email channel respects opt-outs and the 10-sends/10-min/IP rate limit.'),
      },
      {
        t: tr('Analytics & GA4 (📈)'),
        b: tr('The Analytics hub shows P&L, occupancy and portfolio trends, and the app feeds anonymized usage events to Google Analytics 4 so you can see which modules your team actually uses. Page views, notification opens and ticket creations are tracked as events.'),
      },
      {
        t: tr('Backups, exports & audit trail'),
        b: tr('Super-admin panel (Settings → Admin):\n\n• One-click DB snapshot + JSON export of the whole workspace\n• Audit log viewer — the latest 50 events (who did what, when)\n• GDPR export — per-tenant JSON (leases, invoices, payments) from any tenant drawer\n\nBackups are kept on a rotation and the audit trail persists per the retention setting.'),
      },
      {
        t: tr('Payments & gateways'),
        b: tr('Invoices can be paid online via configured payment gateways (SSLCommerz integration; sandbox in test mode). Each transaction is recorded in gateway_tx with status tracking — pending → success/failure — and receipts reconcile automatically in the Collections view.'),
      },
      {
        t: tr('Web push & cross-device'),
        b: tr('Beyond email, the app uses Web Push (VAPID) so alerts arrive on desktop/mobile browsers even when the tab is closed. Subscribe in Settings → Browser notifications; each device is tracked and dead subscriptions are cleaned automatically. The app is a PWA — install it to the home screen for a native feel.'),
      },
      {
        t: tr('Money flow: invoice → payment → receipt → statement'),
        b: tr('Understanding how the numbers connect helps you use Finance correctly:\n\n1. Invoice — you generate a rent invoice per lease (Draft → Sent)\n2. Payment — the tenant pays (cash, bank, or online gateway)\n3. Receipt — you record the payment; the invoice flips to Paid\n4. Collections — the reconciled view of who owes what\n5. Statement — the monthly owner statement summarises gross, collected and outstanding per property\n\nEvery step updates the same ledger, so the Overview KPIs always agree with the module screens.'),
      },
      {
        t: tr('Importing & exporting your data'),
        b: tr('You are never locked in:\n\n• ⬇ CSV — most lists (invoices, tenants, tickets, notices) export the current filtered set\n• 📦 GDPR export — from any tenant drawer, download full JSON (leases, invoices, payments)\n• 💾 Backups — the super-admin panel can snapshot the database and export the whole workspace\n• 📄 Templates — document templates generate lease letters and invoices from stored data\n\nCSV exports respect your active filters and view mode, so you export exactly what you see.'),
      },
      {
        t: tr('Mobile & PWA tips'),
        b: tr('The app is a PWA — install it to your home screen for a native feel:\n\n• iPhone: Share → Add to Home Screen; Android: browser menu → Install app\n• Web push works on desktop and mobile browsers (Settings → Browser notifications)\n• The layout is responsive: sidebars collapse, tables scroll, drawers go full-screen\n• Tip: keep the app open in a browser tab so push subscriptions stay alive\n\nEverything works from the phone — pay, post notices, answer tickets, check KPIs.'),
      },
    ],
  },
  {
    id: 'dev', ico: '🧑‍💻', title: tr('Developer API (for integrations)'),
    items: [
      {
        t: tr('API overview & base URL'),
        b: tr('KRTaker exposes a JSON API at https://krtaker.com/api/ (staging: https://test.krtaker.com/api/). Every feature in the dashboard is an API call, so anything the UI can do, an integration can do.\n\n• POST requests carry JSON (Content-Type: application/json)\n• GET is only allowed for read-only whitelisted actions\n• Every response is JSON: { \"ok\": true, ... } or { \"ok\": false, \"error\": \"...\" }\n• Authenticated calls send: Authorization: Bearer <token>\n• HTTP status codes: 200 ok · 400 bad request · 401 unauthorized · 403 access denied · 404 missing · 429 rate limited · 500/503/504 transient\n\nEndpoints are named app-* (e.g. app-login, app-bootstrap, app-crud, app-statements). The official dashboard client retries 500/503/504 up to 3 times with backoff — integrations should do the same.'),
      },
      {
        t: tr('Authentication: login → token → bearer'),
        b: tr('1) POST app-login with { "email": "...", "password": "..." }.\n2) On success you get { "ok": true, "token": "<session-token>", "user": { ... } }.\n3) Send that token on every later call in the Authorization header, formatted as the word Bearer, a space, then your session token.\n\nAccounts are role-based: subscribers (kind=sub) and staff (kind=staff). A 2FA-protected superadmin login is two-step: the first POST returns { "need_2fa": true, "method": "totp" | "email" } with a 401; send the code back as { "2fa_code": "..." } (or add "2fa_alt": "email" to get an emailed code instead).\n\nPOST app-me returns the current user profile, plan catalog and subscription. POST app-logout revokes the token. Sessions expire after the configured TTL (default 7 days; superadmin 12h) — on a 401, re-login and refresh the token. POST app-sessions lists active sessions and supports revoke / revoke_others / revoke_all (pass an empty action {} to just list).'),
      },
      {
        t: tr('The app-crud endpoint (create/update/delete)'),
        b: tr('Most record types (properties, units, tenants, leases, invoices, receipts, tickets, partners, staff, vendors, compliance, cases…) use one generic endpoint:\n\nPOST app-crud\n{ \"action\": \"create\" | \"update\" | \"delete\",\n  \"collection\": \"properties\",\n  \"data\": { \"name\": \"Mirpur Heights\", ... },  // create/update only\n  \"id\": \"P-001\" }                                // update/delete only\n\n• Each collection has a fixed allow-list of fields — unknown fields are silently dropped\n• Subscribers can never set ownership (sub_email) directly; the server stamps it\n• Role + plan gates apply per collection (403 if your role cannot CRUD it)\n• Tenants/partners cannot edit or delete records\n• Delete is hard-delete on the primary collection row; related rows are handled per collection\n\nList endpoints (app-bootstrap, app-statements, app-compliance, etc.) are typically GET-whitelisted or accept an empty action {} in a POST to return the current set.'),
      },
      {
        t: tr('Bootstrap & master data'),
        b: tr('POST/GET app-bootstrap returns the full working set for the logged-in user\'s role:\n\n• Staff-ish roles (superadmin, owner, manager, svc_mgr, legal, crm, accountant, hr) get all properties, units, tenants, leases, invoices, receipts, payments, tickets, partners, staff and support rows\n• Tenant/partner roles get only their own rows\n\nOther master-data endpoints: app-profile (read/update your profile), app-settings-get / app-settings-save (per-user notification prefs — send only the fields you want to change), app-theme (public branding, no auth), app-security (2FA methods, password), app-setup-done (mark the guided-setup wizard complete for a subscriber).'),
      },
      {
        t: tr('Finance endpoints (invoices, receipts, money)'),
        b: tr('• app-invoice-auto — auto-generate monthly invoices: { \"month\": \"YYYY-MM\" }; accepts a service key OR owner/manager/accountant auth\n• app-invoice-email — email an invoice to its tenant (10/10-min rate limit)\n• app-invoice-pay — record a payment against an invoice; flips it to Paid and issues a receipt\n• app-invoice-print — printable invoice (GET)\n• app-collections-summary / app-collections-run — who owes what, and run the collection reconciliation\n• app-payment-recon / app-payment-reconcile / app-payment-proof — payment matching & proof records\n• app-receipt-email — email a receipt (10/10-min rate limit)\n• app-refund — process a refund against a receipt\n• app-statements / app-statement-email — monthly owner statements; the email action supports a schedule (day 1–28) and auto-send toggle, service-key-gated\n• app-remit — NRB remittance handling\n• app-settlement-report — settlement report\n• app-utility-bill-generate / -list / -pay / -preview / -tariff-get / -tariff-save — utility billing\n\nPayment-init is throttled harder: 6/min and 20/hr per IP.'),
      },
      {
        t: tr('Portfolio & property endpoints'),
        b: tr('• app-crud with collection properties / units / tenants / leases — the core hierarchy\n• app-hando-create / -list / -get / -save / -delete — move-in handover checklists\n• app-onboarding — onboarding workflow\n• app-leads — prospect pipeline\n• app-doc-* — documents: app-doc-list, app-doc-view, app-doc-download, app-doc-upload, app-doc-delete, app-doc-cat, app-doc-vault\n• app-tpl-* — document templates: list, get, save, delete, dup, render, reset\n• app-insurance — policy records\n• app-gdpr-export — per-tenant JSON export (leases, invoices, payments)\n• app-photo — tenant/unit photos (GET binary, POST multipart via app-doc-upload / dedicated upload)\n\nUploads use multipart/form-data with the same Authorization: Bearer header.'),
      },
      {
        t: tr('BMS & operations endpoints (maintenance, vendors, meters)'),
        b: tr('• app-maintenance — maintenance tickets (list + create; SLA tracked server-side)\n• app-sla — SLA configuration & status\n• app-vendors — vendor marketplace (RFQs, work orders, payouts)\n• app-meter-list / app-utility-bill-* — meter readings & utility invoices\n• app-gate — gate visit security log\n• app-samity — community committee records\n• app-staffwatch — staff attendance watch\n• app-build — construction project tracker\n• app-systems / app-smarthome — building systems & smart-home devices\n• app-firesafety — fire certificates, drills, equipment checks\n• app-inspections — scheduled inspections\n• app-kr-wa — WhatsApp reminders\n• app-tenant-chat / app-tenant-chat-send — tenant chat\n• app-tenant-note / app-tenant-note-save — tenant notes\n• app-tenant-me — tenant portal identity\n\nMaintenance tickets carry a liability flag (Landlord/Tenant/Shared) and an SLA clock — breached jobs raise alerts automatically.'),
      },
      {
        t: tr('Community, support & notices'),
        b: tr('• app-notice-create (with email=1 to broadcast), app-notice-list, app-notice-recipients — notice board + email broadcast (10/10-min rate limit; respects tenant opt-outs)\n• app-support-ticket — the help desk: create/comment/status/prio/thread in one endpoint (also app-ticket-create, app-ticket-comment, app-ticket-status, app-ticket-thread)\n• app-referral-generate / -list / -update — referral codes & rewards\n• app-trust — NID/identity trust records\n• app-kyc — Know-Your-Customer records\n• app-concierge — resident services\n• app-land — land parcel registry\n• app-nrb — NRB features\n• app-legal — legal & compliance records\n• app-compliance — compliance certificates with expiry\n\nPOST app-support-ticket with an empty action {} returns the ticket list; sub-actions handle create, replies, status transitions and priority changes.'),
      },
      {
        t: tr('Automation & AI endpoints'),
        b: tr('• app-reminder-config / app-reminder-save / app-reminder-run / app-reminder-summary — rent-reminder schedule and manual run\n• app-rent-due-push — push notifications for rent due\n• app-rent-config-get / -save — rent configuration\n• app-renewal-* — lease renewals (list, offer, respond, decide, create)\n• app-ai-chat — ask the AI Caretaker (KR) a question in plain language\n• app-ai-meta — AI metadata\n• app-kr-alert — alert scanner results (SLA/compliance/arrears/renewals)\n• app-analytics — GA4/analytics read (accepts a service key, read-only)\n• app-push — web-push subscription management\n• app-sms — SMS records (go-live pending provider key)\n• app-gateways — payment gateway configuration\n• app-premium-* — plans, subscribe, cancel, billing\n• app-email-tpl-* / app-email-preview — transactional email templates\n• app-export / app-backup / app-audit / app-error-log — admin exports, backups, audit trail, error log\n\nService keys (kr-svc-...) are accepted on read-only endpoints (analytics, build, statement email); write endpoints still require a real user token.'),
      },
      {
        t: tr('Rate limits & throttling'),
        b: tr('The API throttles aggressively to protect deliverability and stop abuse:\n\n• Email sends (invoice-email, receipt-email, notice broadcast, tenant-remind): 10 per 10 minutes per IP — the response includes retry_after (seconds) and a Retry-After header; the window is rolling\n• Payment-init: 6 per minute and 20 per hour per IP\n• Login: repeated failures trigger an account lockout (sec_lockout_minutes, default 15; clamped 1–1440)\n• Bot guard: unauthenticated form endpoints require a proof-of-work (pow) — sha256(window:nonce) with ≥12 leading zero bits, window = floor(epoch/300), server accepts ±1 window — plus a honeypot field (hp) and page-load timestamp (ft)\n\nOn 429, back off for retry_after seconds. The dashboard client also retries 500/503/504 with exponential backoff — mirror that behaviour in your integration.'),
      },
      {
        t: tr('Security model & error handling'),
        b: tr('Every endpoint is gated by three layers:\n\n1. Authentication — a valid Bearer token (401 otherwise)\n2. Role & plan — effective_modules() decides what your role can see; owners see everything, staff see their modules (403 otherwise)\n3. Row scope — tenant/partner accounts only touch their own rows; subscribers can never set ownership fields\n\nCommon errors and fixes:\n• 401 Unauthorized — token missing/expired; re-login\n• 403 Access denied — module or CRUD not allowed for your role/plan\n• 400 Invalid/Unknown action — check the action + required fields; list endpoints want {} (or GET if whitelisted)\n• 429 — rate limited; honor retry_after\n• 500/503/504 — transient (SQLite lock, upstream); retry with backoff\n• Empty response body — wrong base URL or stale host; use https://krtaker.com/api/\n\nAll audit-worthy operations (login, create, update, delete, exports) are written to the audit log.'),
      },
      {
        t: tr('Example: end-to-end invoice flow'),
        b: tr('A complete integration that bills a tenant:\n\n1) Login — POST app-login { "email": "owner@...", "password": "..." } → { "ok": true, "token": "abc123" }\n2) Generate — POST app-invoice-auto { "month": "2026-09" }, passing the login token in the Authorization header\n3) List — POST app-bootstrap {} (or GET) to read the new invoice id/status\n4) Email — POST app-invoice-email { "id": "INV-1043" } (respect the 10/10-min limit)\n5) Payment — POST app-invoice-pay { "id": "INV-1043", "amount": 45000, "method": "bKash" } → invoice flips to Paid, receipt issued\n6) Verify — GET app-collections-summary → outstanding drops by the amount\n7) Statement — monthly, POST app-statement-email { "month": "2026-09", "day": 1 } with the service key (cron)\n\nEvery step returns { "ok": true } plus data; failures always carry a human-readable "error" string.'),
      },
      {
        t: tr('Webhooks, pushes & external services'),
        b: tr('KRTaker integrates outward so your other tools can react:\n\n• Web push — POST app-push manages VAPID subscriptions; the app can push to subscribed devices even when the tab is closed (browser must be running)\n• GA4 — usage events (page views, notification opens, ticket creations) flow to Google Analytics 4 for the workspace\n• Payment gateways — app-gateways + app-gateway-cleanup manage gateway config (SSLCommerz); transactions are recorded in gateway_tx with pending → success/failure status\n• Email — all outbound mail goes through the configured SMTP queue with per-class master switches and per-user toggles; opt-outs are respected everywhere\n• WhatsApp — app-kr-wa sends WhatsApp reminders to the configured number\n• SMS — app-sms is wired for a provider (go-live pending the provider key)\n\nFor cron-style automation (monthly statements, rent reminders), use the service key (kr-svc-...) which is accepted on the read-only/automation endpoints without a user session.'),
      },
    ],
  },
  {
    id: 'faq', ico: '❓', title: tr('FAQ & troubleshooting'),
    items: [
      {
        t: tr('I stopped getting emails — why?'),
        b: tr('Check in order: (1) your own toggles in Settings → Notifications; (2) the admin master switches in Settings → App; (3) your spam folder — add KRTaker to your contacts; (4) the mail queue — a heavy batch (notices, statements) can hit the 10/10-min rate limit; wait and re-run.'),
      },
      {
        t: tr('Push notifications stopped arriving'),
        b: tr('The browser must be running for web push. Re-open the app and check Settings → Browser notifications still shows your device. If the browser permission was revoked, re-enable it and subscribe again. Old dead subscriptions are cleaned automatically.'),
      },
      {
        t: tr('My role was switched / I can\'t see a module'),
        b: tr('Roles show only permitted modules. If you were switched to a subordinate role (👁 icon in the sidebar bottom), press "↩ Back to my account". If a module is genuinely missing, ask the account admin to adjust your role modules.'),
      },
      {
        t: tr('I hit "rate limit exceeded"'),
        b: tr('Broadcast emails are throttled to 10 per 10 minutes per IP. Wait a few minutes — the counter resets on a rolling window — then retry. This protects your domain reputation so your emails do not land in spam.'),
      },
      {
        t: tr('Can I use KRTaker on mobile?'),
        b: tr('Yes. Open app.krtaker.com on your phone and log in — the interface adapts to small screens. For the best experience, install it to your home screen (PWA): iPhone → Share → Add to Home Screen; Android → menu → Install app. Push notifications also work on mobile browsers once you subscribe in Settings → Browser notifications.'),
      },
    ],
  },
]

// search filter (title + body)
const filtered = computed(() => {
  const s = q.value.trim().toLowerCase()
  if (!s) return SECTIONS
  return SECTIONS.map(sec => ({
    ...sec,
    items: sec.items.filter(it => (it.t + ' ' + it.b).toLowerCase().includes(s)),
  })).filter(sec => sec.items.length)
})

function toggle(sid, iid) {
  const k = sid + ':' + iid
  open.value = { ...open.value, [k]: !open.value[k] }
}
function isOpen(sid, iid) { return !!open.value[sid + ':' + iid] }
function toggleAll(sec, force) {
  const k = sec.id + ':all'
  const on = force !== undefined ? force : !open.value[k]
  open.value = { ...open.value, [k]: on }
}
function allOpen(sec) { return !!open.value[sec.id + ':all'] }
function go(path) { router.push(path) }
</script>

<template>
  <div>
    <div class="page-head">
      <div>
        <h1>📚 {{ lang === 'bn' ? 'উইকি ও সাহায্য' : 'Wiki &amp; Help' }}</h1>
        <div class="sub">{{ tr('Visual guides, alerts, notifications, email & security') }}</div>
      </div>
    </div>

    <!-- search -->
    <div class="panel" style="padding:14px 16px;margin-bottom:14px">
      <input v-model="q" :placeholder="lang === 'bn' ? '🔍  উইকি খুঁজুন… (যেমন 2FA, টিকেট, ইনভয়েস, পুশ, ডাইজেস্ট)' : '🔍  Search the wiki…  (e.g. 2FA, ticket, invoice, push, digest)'"
        style="width:100%;padding:11px 14px;border-radius:12px;border:1px solid var(--border);background:var(--bg);color:var(--text);font-size:14px;outline:none">
    </div>

    <div v-if="!filtered.length" class="panel" style="padding:40px 20px;text-align:center;color:var(--text-mute)">
      {{ tr('No articles match') }} “{{ q }}”.
    </div>

    <div v-for="sec in filtered" :key="sec.id" class="panel" style="padding:6px 16px 14px;margin-bottom:14px">
      <div style="display:flex;align-items:center;gap:10px;padding:12px 0 10px;border-bottom:1px solid var(--border)">
        <span style="font-size:20px">{{ sec.ico }}</span>
        <div style="flex:1">
          <div style="font-weight:800;font-size:15px">{{ sec.title }}</div>
          <div class="c-sub" style="font-size:11.5px">{{ sec.items.length }} {{ lang === 'bn' ? 'টি নিবন্ধ' : (sec.items.length === 1 ? 'article' : 'articles') }}</div>
        </div>
        <button class="btn-ghost" style="padding:6px 12px;font-size:12px" @click="toggleAll(sec)">{{ allOpen(sec) ? tr('Collapse') : tr('Expand all') }}</button>
      </div>

      <div v-for="it in sec.items" :key="it.t" style="border-bottom:1px solid var(--border)">
        <div style="display:flex;align-items:center;gap:8px;padding:12px 4px;cursor:pointer;user-select:none" @click="toggle(sec.id, it.t)">
          <span style="font-size:12px;color:var(--text-mute);width:16px;flex-shrink:0">{{ isOpen(sec.id, it.t) ? '▾' : '▸' }}</span>
          <span style="font-weight:700;font-size:13.5px;flex:1">{{ it.t }}</span>
          <span v-if="it.tag" class="badge b-blue" style="font-size:10px">{{ it.tag }}</span>
        </div>
        <div v-if="isOpen(sec.id, it.t)" style="padding:2px 4px 14px 28px">
          <GuideScreen v-if="it.g" :variant="it.g.variant" :url="it.g.url" :highlights="it.g.highlights" />
          <div style="white-space:pre-wrap;line-height:1.65;font-size:13px;color:var(--text)">{{ it.b }}</div>
        </div>
      </div>
    </div>

    <div class="panel" style="padding:16px;margin-bottom:20px">
      <div style="font-weight:800;font-size:13.5px;margin-bottom:10px">{{ lang === 'bn' ? 'আরও সাহায্য দরকার?' : 'Still stuck?' }}</div>
      <div style="display:flex;gap:10px;flex-wrap:wrap">
        <button class="btn-ghost" style="padding:9px 16px;font-size:12.5px" @click="go('/support')">🎫 {{ lang === 'bn' ? 'সাপোর্ট টিকেট খুলুন' : 'Open a support ticket' }}</button>
        <button class="btn-ghost" style="padding:9px 16px;font-size:12.5px" @click="go('/settings')">⚙️ {{ lang === 'bn' ? 'আমার সেটিংস দেখুন' : 'Review my settings' }}</button>
      </div>
    </div>
  </div>
</template>
